config/companion_libs/gmp.in
scripts/build/companion_libs/100-gmp.sh

gmp: Disable --enable-mpbsd if version is >= 5.0.2

---

config/binutils/binutils.in
patches/binutils/2.25/120-sh-conf.patch
patches/binutils/2.25/300-001_ld_makefile_patch.patch
patches/binutils/2.25/300-012_check_ldrunpath_length.patch

This also updates the patches from 2.24.

binutils: Add binutils-2.25

---

scripts/config.guess
scripts/config.sub

From http://git.savannah.gnu.org/gitweb/?p=config.git
Signed-off-by: Ray Donnelly <mingw.android@gmail.com>

config.{sub,guess}: Update to latest

---

patches/newlib/2.0.0/100-fix-optimising-for-space.patch
patches/newlib/2.1.0/100-fix-optimising-for-space.patch

This patch is from Bob Dunlop on patchwork.

Patch newlib-2.xx optimising for space Append flags to CFLAGS_FOR_TARGET rather than replacing.

---

config/companion_tools.in
patches/gcc/4.7.4/100-hardfloat-ld.patch
scripts/build/companion_tools/050-make.sh

These are changes from Bernhard Walle from patchwork.

Patchwork bernhard walle

---

patches/uClibc/0.9.33.2/300-fix-darwin-build.patch

This are change from Andreas Bießmann from patchwork.

uClibc: fix darwin build

---

scripts/patch-rework.sh

Signed-off-by: Led <ledest@gmail.com>

fix bashisms in patch-rework.sh script

---

samples/nios2-elf-mingw32/crosstool.config
samples/nios2-elf-mingw32/reported.by

add sample file for the nios2 architecture.

arch/sample : add sample file for the nios2 architecture

---

scripts/build/libc/mingw.sh

Tested and verified with mingw version 2.0.7, 3.3.0 and 4.0-rc3

Updated script to support mingw versions above major 2

---

config/companion_libs/isl.in

config/isl: bump isl to 0.14 for >=gcc-5.1

---

scripts/build/companion_libs/130-cloog.sh
scripts/build/companion_libs/140-mpc.sh

comp_libs: Fix download locations for cloog and mpc

---

config/kernel/linux.in
scripts/build/kernel/linux.sh

This commit adds support for 4.x and updates longterm versions.

kernel: Update kernel versions

---

config/kernel/linux.in

Stable releases updated last night. Sync versions with kernel.org.

config/kernel: Update with longterm stable releases

---

config/kernel/linux.in

This updates the stable kernel series.

config/kernel: Update kernel versions

---

config/libc/mingw.in
scripts/build/libc/mingw.sh

Update to latest releases and add "DEVEL" version for fetching from git. Contains an example of using https://github.com/crosstool-ng/crosstool-ng/commit/f95b34d52fb2ff58cddbc426f8f008f83734f96f

Windows target

---

config/kernel/linux.in

Update versions:
* 4.0.2 to 4.0.3
* 3.19.7 to 3.19.8
* 3.14.41 to 3.14.42
* 3.10.77 to 3.10.78
* 3.2.68 to 3.2.69

linux: update kernel versions

---

config/debug/strace.in

strace: add versions 4.9 and 4.10

---

config/kernel/linux.in

4.0.4     -> 4.0.5
3.18.14   -> 3.18.16
3.14.43   -> 3.14.44
3.12.43   -> 3.12.44
3.10.79   -> 3.10.80
2.6.32.66 -> 3.6.32.67

kernel: Stable kernel updates

---

config/kernel/linux.in

Add linux-4.1
Remove linux-3.19.8 (EOL'd)
Updates:
* 4.0.5 -> 4.0.6
* 3.14.44 -> 3.14.45
* 3.10.80 -> 3.10.81
* 3.4.107 -> 3.4.108

config/kernel: Update linux kernel versions

---

config/cc/gcc.in

add gcc 5.2
Signed-off-by: Daniel Zimmermann <netzimme@gmail.com>

cc/gcc: add gcc 5.2

---

config/kernel/linux.in

config/linux: Add 4.2 and update stable versions

---

config/debug/gdb.in

gdb: Add gdb-7.10

---

config/libc/musl.in

musl: Update mainline to 1.1.11

---

config/companion_libs/mpc.in

Support mpc 1.0.3 in configuration.

Support mpc V 1.0.3

---

config/companion_libs/mpfr.in

Support mpfr 3.1.3 in configuration.

Support mpfr V 3.1.3

---

patches/gdb/7.10/10-setns-handling.patch

fixes issue crosstool-ng/crosstool-ng#176

gdb-7.10 upstream fix for build problems if CT_GDB_NATIVE=y

---

config/libc/newlib.in
scripts/build/libc/newlib.sh

Added additional newlib specific target cflags with new option
LIBC_NEWLIB_TARGET_CFLAGS.

Newlib specific target cflags

---

.travis.sh
.travis.yml
Makefile.in
config/global/logging.in
configure.ac

Here is a proper implementation of #193.
I have also added the revert of your commits which - if you choose this option - are no longer needed.

Manage Travis-CI build

---

config/debug/gdb.in

Remove CC_GDB_CUSTOM from the version choice.

Remove CC_GDB_CUSTOM from the version choice

---

samples/powerpc-e500v2-linux-gnuspe/crosstool.config

See 1st commit message as to what that entailed.

Fix option names in powerpc-e500v2 sample.

---

config/libc/musl.in

musl-libc: update musl-libc mainline to 1.1.12

---

config/kernel/linux.in

Update current stable and long-term releases:
* 4.2       -> 4.2.3
* 4.1.6     -> 4.1.10
* 3.18.20   -> 3.18.22
* 3.14.51   -> 3.14.54
* 3.12.47   -> 3.12.49
* 3.10.87   -> 3.10.90
* 3.4.108   -> 3.4.109
* 3.2.71    -> 3.2.72
* 3.6.32.67 -> 3.6.32.68

linux: Update linux kernel versions

---

scripts/config.guess
scripts/config.sub

Update config.sub and config.guess from:
* git://git.sv.gnu.org/config.git
See their gitweb:
* http://git.savannah.gnu.org/gitweb/?p=config.git

scripts/config.{sub,guess}: Update from upstream

---

config/libc/mingw.in
scripts/addToolVersion.sh
scripts/build/libc/mingw.sh

See https://github.com/crosstool-ng/crosstool-ng/issues/246

Mingw issue with parallel build.

---

scripts/functions

cosmetic: Do not log state saving/restoring as ERROR.

---

samples/samples.mk

Document {check,update}-samples targets.

---

config/companion_libs/gmp.in

Signed-off-by: Freddie Chopin <freddie.chopin@gmail.com>

gmp: add version 6.1.0

---

config/libc/uClibc.in

uClibc-ng: Update to 1.0.11

---

config/cc/gcc.in

Update to Linaro GCC 5.2-2015.11-2 released on 22/01/2016

config/gcc: Update to Linaro GCC 5.2-2015.11-2

---

config/binutils/binutils.in
patches/binutils/2.26/120-sh-conf.patch
patches/binutils/2.26/300-001_ld_makefile_patch.patch
patches/binutils/2.26/300-012_check_ldrunpath_length.patch
patches/binutils/2.26/310-fix-gold-pthreads-typo.patch
patches/binutils/2.26/320-MinGW-w64-winpthreads-doesnt-have-pthread_mutexattr_settype.patch
patches/binutils/2.26/330-Dont-link-to-libfl-as-its-unnecessary.patch
patches/binutils/2.26/340-Darwin-gold-binary-cc-include-string-not-cstring.patch
patches/binutils/2.26/350-Darwin-Two-fixes-from-Android-NDK-PTHREAD_ONCE_INIT-wcsncasecmp.patch
patches/binutils/2.26/500-sysroot.patch
patches/binutils/2.26/600-poison-system-directories.patch
scripts/addToolVersion.sh

binutils: Add binutils-2.26

---

config/libc/uClibc.in

uClibc-ng: Update to 1.0.12

---

config/debug/gdb.in
patches/gdb/7.11/100-musl_fix.patch
patches/gdb/7.11/101-uclibc-no-gettimeofday-clobber.patch
patches/gdb/7.11/111-xtensa-make-sure-ar_base-is-initialized.patch
patches/gdb/7.11/112-WIP-end-of-prologue-detection-hack.patch

Signed-off-by: Joachim Nilsson <troglobit@gmail.com>

gdb: Add support for v7.11, port patches from v7.10.1 that apply

---

config/libc/glibc.in
scripts/build/libc/glibc.sh

This is the long needed glibc cleanup.
There is still more work to do to clean up this glibc script, but this is a good stopping point for now.

Glibc cleanup

---

config/kernel/linux.in

Kernel revisions updated to match kernel.org.
Signed-off-by: Yogesh Sharma <YogeshASharma@gmail.com>

kernel: Updated kernel revisions

---

config/libc/musl.in

We also remove the old 1.0 series.

musl-libc: Update to 1.1.14

---

scripts/config.guess
scripts/config.sub

config.{sub,guess}: Ran ct-ng updatetools

---

config/arch/sh.in
config/cc/gcc.in.2
config/libc/musl.in
scripts/build/arch/alpha.sh
scripts/build/arch/arm.sh
scripts/build/arch/m68k.sh
scripts/build/arch/microblaze.sh
scripts/build/arch/mips.sh
scripts/build/arch/powerpc.sh
scripts/build/arch/s390.sh
scripts/build/arch/sh.sh
scripts/build/arch/sparc.sh
scripts/build/arch/x86.sh
scripts/build/cc/100-gcc.sh
scripts/build/libc/glibc.sh
scripts/functions

As indicated on IRC, first 10 commits were reviewed and ready to go.

First chunk of multilib changes for merging

---

README.md

README.md: Add mailing list archive/subscription page

---

README.md

I had Ready twice and colums in the wrong order.

Fix waffle.io badges

---

README.md

README.md: Fix a list formatting issue.

---

scripts/build/internals.sh

Fix minor issue introduced by 6f8e89cb5ca061e899bf3feaaf3fecf30d366c3e

populate: Fix undefined awk

---

scripts/config.guess
scripts/config.sub

Update config.guess and config.sub

---

scripts/build/cc/100-gcc.sh

See the comment in the code for details.

Do not run 'make install' in parallel in GCC.

---

config/libc/glibc.in
patches/glibc/2.24/100-Cygwin-doesnt-have-stat64.patch

Signed-off-by: Joachim Nilsson <troglobit@gmail.com>

glibc: Add glibc-2.24

---

patches/gcc/4.9.3/120-gcc-config.gcc-fix-typo-for-powerpc-e6500-cpu_is_64b.patch

The patch provided by the original submitter did not apply cleanly to 4.9.3; had a fuzz 2.
We only allow fuzz 1. Fix up the patch.

Unbreak 4.9.3.

---

config/companion_libs/gettext.in

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crosstool-ng/crosstool-ng/387)

gettext: update to 0.19.7

---

kconfig/conf.c
kconfig/confdata.c
kconfig/symbol.c

This pull request updates our kconfig from the upstream linux kernel.

kconfig: sync upstream changes

---

config/libc/uClibc.in

uClibc-ng: Add 1.0.19

---

config/cc/gcc.in
config/companion_libs.in
config/toolchain.in
patches/gcc/4.8.5/1000-libtool-leave-framework-alone.patch
patches/gcc/4.9.4/1000-libtool-leave-framework-alone.patch
patches/gcc/5.4.0/1000-libtool-leave-framework-alone.patch
patches/gcc/6.3.0/1000-libtool-leave-framework-alone.patch
scripts/build/cc/100-gcc.sh
scripts/build/companion_libs/121-isl.sh
scripts/build/companion_libs/320-libiconv.sh
scripts/build/companion_libs/330-gettext.sh
scripts/build/debug/300-gdb.sh
scripts/build/debug/500-strace.sh
scripts/build/libc/glibc.sh
scripts/crosstool-NG.sh.in

First 3 commits are small clean-ups, last two are supposed to fix macos simple crosses.

Pass flags for build

---

patches/binutils/2.27/999-xtensa-reverse-shift-count.patch

Patch from: https://bugzilla.redhat.com/show_bug.cgi?id=1404857

Fix xtensa after binutils upgrade.

---

Makefile.in
configure.ac
kconfig/Makefile
kconfig/zconf.gperf

Loosely based on:
https://github.com/systemd/systemd/commit/c9f7b4d356a453a01aa77a6bb74ca7ef49732c08

Add a check for gperf function signature.

---

config/libc/uClibc.in

Add uClibc-ng 1.0.21.

---

config/companion_libs/expat.in

Add expat 2.1.1 and 2.2.0.

---

.travis.yml

Hopefully, this makes travis do something useful.

Remove travis samples prone to timeout.

---

patches/strace/4.15/020-use-asm-sgidefs.h.patch

for mips-*-linux-musl. Upstream report:
https://sourceforge.net/p/strace/mailman/message/35615169/

Patch from OpenEmbedded to fix strace build

---

config/libc.in

Typos in linuxthreads/posix config values

---

config/binutils/binutils.in.2
config/libc/mingw.in
configure.ac

... and make the optiont that fetch from Git repositories depend on
the git discovery.

Check for git presence

---

scripts/build/companion_tools/050-make.sh
scripts/build/companion_tools/100-m4.sh
scripts/build/companion_tools/200-autoconf.sh
scripts/build/companion_tools/300-automake.sh
scripts/build/companion_tools/400-libtool.sh

(was EXTRA, should be INFO to be consistent with the rest).

Fix loglevel for steps in companion tools

---

scripts/crosstool-NG.sh.in
scripts/functions

after the CT_Log{Enable,Disable} changes.

Fix log saving/restoring

---

scripts/build/binutils/binutils.sh
scripts/build/cc/100-gcc.sh
scripts/build/companion_libs/100-gmp.sh
scripts/build/companion_libs/110-mpfr.sh
scripts/build/companion_libs/121-isl.sh
scripts/build/companion_libs/130-cloog.sh
scripts/build/companion_libs/140-mpc.sh
scripts/build/companion_libs/200-libelf.sh
scripts/build/companion_libs/210-expat.sh
scripts/build/companion_libs/220-ncurses.sh
scripts/build/companion_libs/320-libiconv.sh
scripts/build/companion_libs/330-gettext.sh
scripts/build/companion_tools/050-make.sh
scripts/build/companion_tools/100-m4.sh
scripts/build/companion_tools/200-autoconf.sh
scripts/build/companion_tools/300-automake.sh
scripts/build/companion_tools/400-libtool.sh
scripts/build/debug/300-gdb.sh
scripts/build/debug/400-ltrace.sh
scripts/build/debug/500-strace.sh
scripts/build/libc/avr-libc.sh
scripts/build/libc/glibc.sh
scripts/build/libc/mingw.sh
scripts/build/libc/musl.sh
scripts/build/libc/newlib.sh

... as its help message says in menuconfig.

Run all configure scripts using ${CONFIG_SHELL}

---

patches/uClibc-ng/1.0.21/120-module.patch

Add patch for init_module/delete_module

---

config/binutils/binutils.in
config/cc/gcc.in
config/companion_libs/cloog.in
config/companion_libs/expat.in
config/companion_libs/gettext.in
config/companion_libs/gmp.in
config/companion_libs/isl.in
config/companion_libs/libelf.in
config/companion_libs/mpc.in
config/companion_libs/mpfr.in
config/companion_tools/automake.in
config/companion_tools/m4.in
config/companion_tools/make.in
config/debug/gdb.in
config/debug/ltrace.in
config/debug/strace.in
config/kernel/linux.in
config/libc/glibc.in
config/libc/uClibc.in
patches/gettext/0.19.8.1/110-Fix-linker-error-redefinition-of-vasprintf.patch
patches/gettext/0.19.8.1/120-Fix-Woe32-link-errors-when-compiling-with-O0.patch
patches/gettext/0.19.8.1/130-Fix-static-Cygwin-x86_64-build-environ-is-always-dllimport.patch
patches/glibc/2.24/110-sh-fix-gcc6.patch
scripts/addToolVersion.sh
scripts/build/debug/400-ltrace.sh

... of the remaining packages. A few updates which have been released since the last batch.

Obsolete versions

---

patches/binutils/2.27/100-missing-break.patch

https://sourceware.org/bugzilla/show_bug.cgi?id=20531
Reported-by: Floessie

Add binutils 2.27 patch

---

config/global/ct-behave.in
config/global/extract.in
scripts/crosstool-NG.sh.in
scripts/functions
scripts/override/__default
scripts/override/install

https://github.com/crosstool-ng/crosstool-ng/issues/538
I need to test it on an actual gentoo installation, will test on monday.

Fix gentoo hang

---

config/libc/uClibc.in.2
scripts/build/arch/arm.sh

Allow one to select uclibceabi/uclibcgnueabi suffix

---

config/toolchain.in

Signed-off-by: Dave Flogeras <dflogeras2@gmail.com>

Fix typo in toolchain.in

---

patches/binutils/2.23.2/310-fix-gold-pthreads-typo.patch
patches/binutils/2.24/310-fix-gold-pthreads-typo.patch

Backport mutextattr typo fix to 2.24 and 2.23.2

---

patches/zlib/1.2.11/110-no-_wopen-cygwin.patch

Fix undefined reference to _wopen on Cygwin

---

scripts/build/companion_libs/220-ncurses.sh

The dependency between them has been removed in Kconfig.

Add --disable-database and --with-fallbacks separately

---

config/cc/gcc.in
config/cc/gcc.in.2
config/companion_libs.in
config/libc/newlib.in.2
scripts/build/cc/100-gcc.sh

Also, GC a lot of options that are the same for all supported releases.

Disable LTO for static toolchain

---

config/cc/gcc.in

Bump Linaro GCC6 to 6.3-2017-02

---

config/cc/gcc.in

Linaro also has new 4.9 and 5.4 releases

---

patches/uClibc-ng/1.0.20/500-no-install-D.patch
patches/uClibc-ng/1.0.21/500-no-install-D.patch
patches/uClibc-ng/1.0.22/500-no-install-D.patch
patches/uClibc/0.9.33.2/500-no-install-D.patch

Fix uClibc{,-ng} build on macos

---

configure.ac
patches/glibc/2.12.1/140-Fix-combreloc-test-BSD-grep.patch
patches/glibc/2.12.2/140-Fix-combreloc-test-BSD-grep.patch
patches/glibc/2.13/140-Fix-combreloc-test-BSD-grep.patch
patches/glibc/2.14.1/140-Fix-combreloc-test-BSD-grep.patch
patches/glibc/2.14/140-Fix-combreloc-test-BSD-grep.patch
patches/glibc/2.15/140-Fix-combreloc-test-BSD-grep.patch
patches/glibc/2.16.0/140-Fix-combreloc-test-BSD-grep.patch
patches/glibc/2.17/140-Fix-combreloc-test-BSD-grep.patch
patches/glibc/2.18/140-Fix-combreloc-test-BSD-grep.patch
patches/glibc/2.19/140-Fix-combreloc-test-BSD-grep.patch
patches/glibc/2.20/140-Fix-combreloc-test-BSD-grep.patch
patches/glibc/2.21/140-Fix-combreloc-test-BSD-grep.patch
patches/glibc/2.22/140-Fix-combreloc-test-BSD-grep.patch
patches/glibc/2.23/140-Fix-combreloc-test-BSD-grep.patch
patches/glibc/2.24/140-Fix-combreloc-test-BSD-grep.patch
patches/glibc/2.25/140-Fix-combreloc-test-BSD-grep.patch
patches/glibc/linaro-2.20-2014.11/140-Fix-combreloc-test-BSD-grep.patch
scripts/build/arch/sparc.sh

SPARC glibc (possibly others) misconfigured on macos

---

patches/uClibc/0.9.33.2/998-dlopen-static.patch

Patch from upstream fixing dlopen from a static app

---

patches/glibc/2.12.1/101-Suppress-GCC-6-warning-about-ambiguous-else-with-Wpa.patch
patches/glibc/2.12.1/102-fix-signed-shift-overlow.patch
patches/glibc/2.12.1/104-unused-variables.patch
patches/glibc/2.12.1/105-misleading-indentation.patch
patches/glibc/2.12.1/106-dl-open-array-bounds.patch
patches/glibc/2.13/101-Suppress-GCC-6-warning-about-ambiguous-else-with-Wpa.patch
patches/glibc/2.13/102-fix-signed-shift-overlow.patch
patches/glibc/2.13/104-unused-variables.patch
patches/glibc/2.13/105-misleading-indentation.patch
patches/glibc/2.13/106-dl-open-array-bounds.patch
patches/glibc/ports-2.12.1/670-support-hard-float-eabi.patch
patches/glibc/ports-2.13/670-support-hard-float-eabi.patch

Reported-by: Austin Beer (brainwave64)

Add ARM patches for 2.12.2/2.13

---

scripts/xldd.in

Cross-ldd: handling e_flags is tricky and depends on arch

---

Makefile.in

... while I continue to work on release script.

Hot fix for 'make install'

---

maintainer/create-release.sh

Add tarball signing to release script

---

config/libc.in

... that resulted in a warning from kconfig

Fix unclosed string

---

scripts/build/cc/100-gcc.sh

Do not create multilib symlinks if not using sysroot

---

maintainer/create-release.sh

Go into subdirectory when checksumming/signing

---

scripts/build/cc/100-gcc.sh

Add symlinks from the libraries' original location to the new one.

---

scripts/build/libc/mingw.sh

Fix MINGW_SECURE_API test

---

README.md
scripts/functions

Make guidelines for bug reporting more explicit

---

config/libc/uClibc.in

Add uClibc-ng 1.0.23 and 1.0.24 releases

---

patches/gcc/4.8.5/111-alpha-bad-eh_frame.patch
patches/gcc/4.9.4/111-alpha-bad-eh_frame.patch
patches/gcc/5.4.0/111-alpha-bad-eh_frame.patch
patches/gcc/6.3.0/111-alpha-bad-eh_frame.patch
patches/gcc/7.1.0/111-alpha-bad-eh_frame.patch

Add patch from GCC #80037

---

patches/glibc/2.25/960-sh4-trap-divdi3.patch

... or older patch(1) breaks over it.
Fixes #726.

Regenerate with --no-renames

---

patches/gcc/6.3.0/1100-ubsan-fix-check-empty-string.patch
patches/gcc/linaro-6.3-2017.02/1100-ubsan-fix-check-empty-string.patch

Taken from the openembedded patchset.
Signed-off-by: Kirill K. Smirnov <kirill.k.smirnov@gmail.com>

patches: Add patch that fixes gcc6 with gcc7

---

patches/gcc/linaro-4.8-2015.06/874-gcc-xtensa-fix-fprintf-format-specifiers.patch
patches/gcc/linaro-4.9-2017.01/875-gcc-xtensa-fix-fprintf-format-specifiers.patch
patches/gcc/linaro-5.4-2017.01/879-gcc-xtensa-fix-fprintf-format-specifiers.patch
patches/gcc/linaro-6.3-2017.02/873-gcc-xtensa-fix-fprintf-format-specifiers.patch

Propagate xtensa fprintf fix to linaro versions.

---

patches/gcc/4.9.4/1100-msp430-string-literals.patch
patches/gcc/5.4.0/1100-msp430-string-literals.patch
patches/gcc/linaro-4.9-2017.01/1100-msp430-string-literals.patch
patches/gcc/linaro-5.4-2017.05/1100-msp430-string-literals.patch

Fix the newly added msp430 sample with other GCC versions

---

Makefile.in

Restore exec permission on ct-ng itself

---

config/libc/uClibc.in

Add uClibc-ng 1.0.25

---

scripts/build/binutils/binutils.sh
scripts/build/cc/100-gcc.sh
scripts/build/debug/300-gdb.sh

Honor CFLAGS_FOR_BUILD

---

Makefile.in
scripts/functions

Fix new framework for running from installed path

---

maintainer/test-packages.sh

Allow test-package.sh to be used in a clean tree

---

config/target.in

Doh, forgot one place to rename the BOTH_ENDIAN option

---

scripts/showSamples.sh

use ${CT_${cc}_VERSION} to show a compiler version

---

scripts/showSamples.sh

showSamples.sh: update outdated variables

---

packages/gcc/7.2.0/370-gcc-plugin-Win-Dont-need-undefined-extern-var-refs-nor-fpic.patch
packages/gcc/7.2.0/810-arm-softfloat-libgcc.patch
packages/gcc/7.2.0/860-cilk-wchar.patch
packages/gcc/7.2.0/891-fix-m68k-uclinux.patch
packages/gcc/7.2.0/952-bionic-errno.patch
packages/gcc/7.2.0/970-crystax.patch
packages/gcc/7.2.0/972-crystax.patch
packages/gcc/7.2.0/973-crystax.patch
packages/gcc/7.2.0/975-crystax.patch
packages/gcc/7.2.0/977-crystax.patch

fix offsets of gcc 7.2.0 patches

---

packages/uClibc-ng/1.0.27/0001-feraiseexcept-2.patch
packages/uClibc-ng/1.0.27/0002-feraiseexcept.patch

More uClibc fixes from upstream

---

scripts/build/debug/300-gdb.sh

Do not build a native gdbserver automatically

---

TODO

Merge a local TODO list

---

scripts/build/libc/mingw-w64.sh

... in the corresponding /lib directory. Mingw-w64 installs it to /bin,
so multiple variants in a multilib configuration override each other.

Preserve each variant of libwinpthread.dll

---

ct-ng.in

... to match the substituted name.
Fixes #966.

Doh. Change the name of the substituted variable

---

Makefile.am
configure.ac
maintainer/git-version-gen

Suggested-by: Chris Packham <judge.packham@gmail.com>

Use git-version-gen to generate version info

---

Makefile.am
maintainer/create-release.sh

Move the last bits of release creation into Makefile.am

---

config/arch/arm.in
packages/linux/package.desc

Disallow linux versions before 3.7 for aarch64

---

packages/automake/1.11.6/0000-escape-left-brace.patch
packages/automake/1.14.1/0000-escape-left-brace.patch

Fix older automake with newer Perl

---

packages/newlib/package.desc

Add a comment explaining why CT_Mirrors is not used

---

packages/binutils/2.31.1/0011-Restore-build-on-x86_64-w64-mingw32.patch

Restore binutils (gold) build on mingw32 host

---

scripts/crosstool-NG.sh

Fix state dir location

---

scripts/functions

It should be possible if fetching a tag/branch, and it may be possible
if fetching a changeset if a server is configured to allow it.
Fixes #986

Try to use 'git fetch --depth 1' if possible

---

scripts/build/arch/powerpc.sh

Generate correct tuple for PowerPC with SPE ABI

---

testing/docker/ubuntu16.04/Dockerfile
testing/docker/ubuntu18.04/Dockerfile
testing/docker/ubuntu18.10/Dockerfile

Add g++ for Ubuntu dockers

---

scripts/functions

Fix detection of missing overlays

---

configure.ac

Still need to check for libtool presence

---

configure.ac

Signed-off-by: Stephan Conrad <stephan@conrad.pics>

added the version 5 to the check of bash versions

---

config/cc/gcc.in
config/global/paths.in
scripts/build/cc/gcc.sh
scripts/functions

... following the buildroot model.

Implement an option to store downloads in subdirs

---

scripts/build/cc/gcc.sh
scripts/build/libc/uClibc.sh
scripts/functions

One more issue discovered in RC1 + a regression in canadian build from first batch.

RC2 fixes, part 2

---

testing/docker/alpine3.8/Dockerfile
testing/docker/common-scripts/ctng-build-sample
testing/docker/common-scripts/ctng-test-basic

Add a Dockerfile for Alpine Linux 3.8

---

scripts/build/libc/musl.sh

Signed-off-by: Dima Krasner <dima@dimakrasner.com>

Fix musl build when CT_SHARED_LIBS=n

---

packages/gcc/8.3.0/0006-libgfortran-missing-include.patch
packages/gcc/8.3.0/0010-crystax.patch
packages/gcc/8.3.0/0013-crystax.patch
packages/gcc/8.3.0/0015-crystax.patch
packages/gcc/8.3.0/0020-ARM-fix-cmse.patch
packages/gcc/8.3.0/0021-arm-Make-arm_cmse.h-C99-compatible.patch

Run GCC 8.3.0 patches through manage-packages.sh -P

---

testing/docker/archlinux/Dockerfile

Archlinux: update keyring before packages

---

config/arch/arm.in

Signed-off-by: Ola Olsson <ola1olsson@gmail.com>

Fix typo in ARM/thumb interworking menuconfig

---

packages/gdb/8.3.1/0005-no-fortify-mingw32.patch
packages/gettext/0.20.1/0001-pthread_sigmask.c-mingw.patch
packages/glibc/2.28/0001-x86-Assume-enable-cet-if-GCC-defaults-to-CET-BZ-2522.patch
packages/glibc/2.29/0002-x86-Assume-enable-cet-if-GCC-defaults-to-CET-BZ-2522.patch
packages/glibc/2.30/0002-x86-Assume-enable-cet-if-GCC-defaults-to-CET-BZ-2522.patch
scripts/build/companion_tools/500-dtc.sh
testing/docker/dmgr.sh
testing/docker/ubuntu19.10/Dockerfile

... and minor fixes to make `ct-ng build-all` pass.

Update docker to ubuntu 19.10

---

maintainer/git-version-gen

Make rpmbuild happy with our unreleased versions

---

packages/glibc/2.19/0017-Fix-cmpli-usage-in-power6-memset.patch
packages/glibc/2.20/0017-Fix-cmpli-usage-in-power6-memset.patch
packages/glibc/2.21/0017-Fix-cmpli-usage-in-power6-memset.patch
packages/glibc/2.22/0017-Fix-cmpli-usage-in-power6-memset.patch
packages/glibc/2.23/0013-Fix-cmpli-usage-in-power6-memset.patch

Integration of the https://patchwork.ozlabs.org/patch/686205/ fix by Joseph Myers

Add powerpc asm fix for glibc 2.19

---

README.md

README.md: Add build status badge

---

.github/workflows/continuous-integration-workflow.yml

CI: Add armv6-nommu-linux-uclibcgnueabi

---

config/cc/gcc.in
scripts/build/cc/gcc.sh

Signed-off-by: Ivan Kukhta <Ivan.Kukhta@acronis.com>

Extend CC_GCC_LIBSSP with manual state

---

packages/libelf/package.desc

Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

libelf: add some mirrors

---

scripts/build/companion_libs/350-newlib_nano.sh

The spec file was missing replacing various libs like libc, libm, etc
with their nano equiv.  So when we linked we'd end up getting libc.a
instead of libc_nano.a.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>

newlib-nano: Fix nano.spec based on CT_NEWLIB_NANO_INSTALL_IN_TARGET

---

config/arch/arm.in
config/cc/gcc.in

Fixes #1699
Signed-off-by: Chen Tao <t.clydechen@gmail.com>

Fix conflict multilibs options

---

scripts/config.guess
scripts/config.sub

Update config.sub and config.guess

---

config/libc/newlib.in

newlib: fix conflicting configure options

---

configure.ac

Some updates to configure.ac since 2.70

Update configure ac

---

packages/gcc/10.4.0/0010-fixinc-don-t-fix-machine-names-in-__has_include-.PR.patch
packages/gcc/11.3.0/0010-fixinc-don-t-fix-machine-names-in-__has_include-.PR.patch
packages/glibc/2.36/0002-Mimic-kernel-defition-for-BLOCK_SIZE.patch
packages/glibc/2.36/0003-Use-compile_c_snippet-to-check-linux_mount.h.patch
packages/glibc/2.36/0004-Fix_sys_mount.h_usage_with_kernel_headers.patch
packages/glibc/2.36/0005-Fix-enum-fsconfig_command-detection-in-sys_mount.h.patch

Reported-by: milkylainen (IRC)

Backport fixes for glibc and gcc to fix interactions with kernel headers

---

debian/control

Add unzip and python3-dev
Fixes #1905

Add missing dependencies for Debian build

---

config/cc/gcc.in
scripts/build/cc/gcc.sh
scripts/build/libc/avr-libc.sh

Signed-off-by: Quentin Boswank <qubos@outlook.de>

Add option to re-enable libstdc++ at avr

---

scripts/build/debug/300-gdb.sh

I noticed that even when the static toolchain and static gdb options are enabled, `gdb` is the only binary in the output that is dynamically linked, which is just due to libtool vs. linking directly. The approach here is borrowed from `scripts/build/binutils/binutils.sh`.

fix static gdb

---

config/config.in
config/config_utils.in
config/configure.in.in
config/kernel/linux.in
configure.ac

Check for rsync in Kconfig rather than ./configure

Better check for rsync

---

scripts/build/companion_libs/400-gnuprumcu.sh

In canadian builds, the target toolchain running on the build machine is not compiling and installing target Newlib.  Thus it cannot by itself link target executables.  This results in errors for gnuprumcu package when its configure script attempts to test the compiler:
.../ld: cannot find crt0.o: No such file or directory
configure:3738: error: C compiler cannot create executables
Fix by passing the host toolchains's sysroot in target CFLAGS.
While at it, also add a missing passing of target LDFLAGS.
Successfully tested the following canadian builds:
x86_64-unknown-linux-gnu,pru
x86_64-w64-mingw32,pru
arm-unknown-linux-gnueabihf,pru

gnuprumcu: Pass host sysroot to build toolchain

---

scripts/build/companion_libs/070-zstd.sh

- multithreading enabled
- release mode

Optimize zstd we build

---

scripts/build/companion_libs/100-gmp.sh

Fixes #2321 
Credit to @jimbomorrison for spotting it.

Fix missing $ for variable

---

.github/workflows/continuous-integration-workflow.yml

Helps finding regressions like #2315 and #2316

CI: add riscv64-unknown-linux-gnu

---

config/arch/sh.in
config/target.in
scripts/build/arch/sh.sh
scripts/config.sub

A lot of the old code didn't even work
Closes #2328 
Signed-off-by: QBos07 <qubos@outlook.de>

Add the FPU options for SuperH
