scripts/build/cc/gcc.sh, scripts/build/libc/newlib.sh
These two patches have newlib match other libcs in the do_libc_start_files function by copying their headers from source to CT_HEADERS_DIR.
The second patch then makes copy_headers=y the default in gcc.sh for all modes, picking up the new headers copied from newlib by the first patch (contrary to the comment that there are no headers to copy for baremetal in the 'static' and 'baremetal' modes of do_cc_core_backend) 
Believe this should resolve #18
=> Newlib headers for Canadian Crosses

config/cc/gcc.in, patches/gcc/4.8.4/001_gcc_bug_62231.patch, patches/gcc/4.8.4/002_gcc_bug_62231.patch, patches/gcc/4.8.4/003-PR57717-E500v2.patch
This merge request adds gcc 4.8.4 and along with patches for powerpc-e500v2-linux-gnuspe. I removed the update of the sample/powerpc-e500v2-linux-gnuspe so that this merge request can be accepted.
=> Adding upstream patches of powerpc-e500v2-linux-gnuspe

config/arch/nios2.in, scripts/build/arch/nios2.sh
add the nios2 architecture to crosstool-ng.
Signed-off-by: Daniel Zimmermann <netzimme@gmail.com>
=> arch/nios2:add nios2

scripts/build/binutils/binutils.sh, scripts/build/cc/gcc.sh, scripts/build/debug/300-gdb.sh, scripts/build/debug/400-ltrace.sh, scripts/build/libc/glibc.sh, scripts/build/libc/newlib.sh
Prirotize http downloads before ftp downloads.
By having http download first, those using proxy will work with the
current download mechnism.
This tells me that that mechnism needs to be updated.
(proxy support and/or kconfig toggles)
closes #3
=> scripts/*/*.sh: prioritize http downloads

patches/glibc/2.16.0/500-fix-parsing-of-numeric-hosts-in-gethostbyname_r.patch
This patch fixes the so-called "GHOST" buffer overflow in glibc 2.16.
See http://www.openwall.com/lists/oss-security/2015/01/27/9.
Signed-off-by: Bernhard Walle <bernhard@bwalle.de>
=> libc/glibc: Add patch to fix CVE-2015-0235

config/binutils/binutils.in, config/libc/glibc.in
With gcc and gdb, it's default to not enable linaro support unless a
knob is enabled to "show linaro versions".
This patch adds the same knob to binutils and glibc.
This change was missing from #24
=> config: Add config knob for linaro

config/libc/newlib.in
I forgot about newlib in 081aba3fdc223e028930b156040dd6b38174a0c3.
This commit adds showing/hiding linaro versions for newlib.
Signed-off-by: Bryan Hundven <bhundven@erado.com>
=> config: Add show linaro config knobs for newlib

scripts/build/cc/gcc.sh
Without this canadion cross builds create invalid symlinks: When `do_cc_core_backend` is called there is no `${CT_TARGET}-gcc` in the install directory. Therefore `ext` is empty and we create a link to `${CT_TARGET}-gcc`. The final compiler step then installs `${CT_TARGET}-gcc.exe` and creates a working `${CT_TARGET}-cc.exe` symlink but we still keep the invalid link as well.
Tested with various cross/canadian cross compilers with windows/linux hosts.
=> Only create ${CT_TARGET}-cc${ext} symlink if ${CT_TARGET}-gcc exists

scripts/build/libc/glibc.sh
Glibc actually does create a build executable.  It's under sunrpc and it's
called cross-rpcgen.  It uses gettext, so if that's not available in a standard
place on your system (for example if you're using Mac OS X and Homebrew), then
you are all out of luck.
=> bugfix: pass extra build CFLAGS and LDFLAGS to glibc

patches/binutils/2.25/300-012_check_ldrunpath_length.patch
Here, the exact size of a not empty string is useless.
=> Do not use strlen to check that a string is empty

docs/B - Known issues.txt
Cygwin no longer supports managed mounts, enabling case-sensitivity in Cygwin requires changing the registry.
FAQ number has also changed.
=> Update case-sensitivity information for Cygwin

kconfig/zconf.gperf
When building on Mac OS, we don't seem to have offsetof when we need it for
gperf-generated code.   This patch solves that issue.
Signed-off-by: Lawrence D'Anna <larry@elder-gods.org>
=> build compat fix for mac os: define offsetof if it's missing

config/libc/glibc.in
2.21 was released yesterday, announcement: https://sourceware.org/ml/libc-alpha/2015-02/msg00119.html
I have compile-tested this with a mips-multilib configuration, but apart from that I can not guarantee anything :)
Should/can we encode the minimum requirement for gcc 4.6 mentioned in that mail somewhere?
=> Add glibc 2.21

config/cc.in
There are other languages which work with bare metal compilers. As an example crosstool-ng is recommended to build D/GDC bare metal compilers.
Signed-off-by: Johannes Pfau <johannespfau@gmail.com>
See http://wiki.dlang.org/GDC/Cross_Compiler/crosstool-NG
=> Display 'Other languages' for bare metal as well

patches/ltrace/0.7.3/110-ltrace.git-8c3674c86688a79a8689772c3d0c84d6e7aaa118.patch
to avoid a gcc 5.1.0 error add a patch for ltrace 0.7.3
Signed-off-by: Daniel Zimmermann <netzimme@gmail.com>
=> debug/ltrace : avoid a gcc 5.1.0 error

config/cc/gcc.in
This change needs another change from pull request #81, but it's kind of
a chicken/egg scenario. The 'select's in CC_GCC_5_1 need to be
refactored a bit, and would be easier to test if gcc-5.1.0 was commited.
Most of the refactoring will happen with CC_GCC_HAS_GRAPHITE.
=> config: Add gcc-5.1.0

config/cc/gcc.in, config/companion_libs/isl.in
As per: https://gcc.gnu.org/gcc-5/changes.html
"The Graphite framework for loop optimizations no longer requires the
CLooG library, only ISL version 0.14 (recommended) or 0.12.2. The
installation manual contains more information about requirements to
build GCC."
This change helps to avoid version badness.
=> complibs: Update requirements for gcc-5.1

config/binutils/binutils.in, config/libc/glibc.in, config/libc/newlib.in
This commit introduces a "show linaro versions" for newlib, binutils,
and glibc.
=> config: Add binutils, newlib, and glibc linaro configuration

scripts/showSamples.sh
This change modifies the use of sed and awk to use the variables set by
paths.sh during the installation process of crosstool-NG.
=> showSamples: Update to use variables from paths.sh

scripts/addToolVersion.sh, scripts/crosstool-NG.sh.in, scripts/saveSample.sh.in
This commit changes sed, awk, and grep to use the ones we found during
configure time. This helps make the build more consistent.
=> scripts: If paths.sh is included, use the variables

scripts/functions
Pass cset as ref=somename to use this feature. CT_GetGit echos
the cset sha1 on exit since the caller will need to know that
information as it forms part of the downloaded tarball name.
Signed-off-by: Ray Donnelly <mingw.android@gmail.com>
=> CT_GetGit: Allow cset to be a ref (branch or tag)

config/libc/mingw.in
While we do want users to be able to use the mingw from git, being under
the experimental umbrella makes it more obvious that this should not be
used as a production toolchain.
=> mingw: WINAPI_V_DEVEL should depend on EXPERIMENTAL

config/debug/gdb.in
As per: http://www.gnu.org/software/gdb/download/ANNOUNCEMENT
========================================================================
GDB 7.9.1 brings the following fixes and enhancements over GDB 7.9:
* PR build/18033 (C++ style comment used in gdb/iq2000-tdep.c and
gdb/compile/compile-*.c)
* PR build/18298 ("compile" command cannot find compiler if tools
configured with triplet instead of quadruplet)
* PR tui/18311 (Random SEGV when displaying registers in TUI mode)
* PR python/18299 (exception when registering a global pretty-printer
in verbose mode)
* PR python/18066 (argument "word" seems broken in Command.complete
(text, word))
* PR pascal/17815 (Fix pascal behavior for class fields with
* testcase)
* PR python/18285 (ptype expr-with-xmethod causes SEGV) …
=> gdb: add gdb 7.9.1

config/kernel/linux.in
In this update the following kernels updated:
* 4.0.3 -> 4.0.4
* 3.18.13 -> 3.18.14
* 3.14.42 -> 3.14.43
* 3.12.42 -> 3.12.43
* 3.10.78 -> 3.10.79
* 3.2.68 -> 3.2.69
* 2.6.32.65 -> 3.6.32.66
Also, let's remove the older EOL'd kernels.
This makes updating kernel versions easier.
=> kernel: Update versions. Remove older kernels

patches/ncurses/5.9/100-ncurses-5.9-gcc5-buildfixes-1.patch
This patch comes from here:
http://archive.linuxfromscratch.org/mail-archives/lfs-dev/2015-April/070101.html
This message explains the error:
http://archive.linuxfromscratch.org/mail-archives/lfs-dev/2015-April/070099.html
=> ncurses: Add gcc5 build patch

scripts/populate.in
The gconv modules are present in the (e)glibc toolchains, and some
applications directly link with one or more of those modules (even
though the classic way of using them is by dlopen()ing them).
So, also look in /usr/lib/gconv when searching for libraries.
Signed-off-by: "Yann E. MORIN" <yann.morin.1998@free.fr>
=> populate: also search for gconv modules

scripts/addToolVersion.sh
Since gcc moved from CC_ to CC_GCC_, addToolVersion neeeded to be
updated.
=> addToolVersion: multi_cc: update addToolVersion

config/libc/musl.in
This commit updates the version knobs so that oldconfig does the right
thing when we bump versions.
Also, we update stable to 1.0.5 and experimental to 1.1.9.
=> musl: Update versions

config/cc/gcc.in
This change makes the 5.1.0 version knob consistant with previous gcc
versions.
=> config/gcc: Fix gcc 5.1.0 version knob

scripts/functions
when specifying a custom kernel provided as a tar ball, the tar ball gets symlinked. the -e test will fail for symbolic links, i had to add the -L test as well.
=> Update functions to grok symlinks

patches/gcc/5.1.0/100-libitm-fixes-for-musl-support.patch, patches/gcc/5.1.0/101-fixincludes-update-for-musl-support.patch, patches/gcc/5.1.0/102-unwind-fix-for-musl.patch, patches/gcc/5.1.0/103-libstdc++-libgfortran-gthr-workaround-for-musl.patch, patches/gcc/5.1.0/104-musl-libc-config.patch, patches/gcc/5.1.0/105-add-musl-support-to-gcc.patch, patches/gcc/5.1.0/106-mips-musl-support.patch, patches/gcc/5.1.0/107-x86-musl-support.patch, patches/gcc/5.1.0/108-arm-musl-support.patch, patches/gcc/5.1.0/109-aarch64-musl-support.patch
This commit adds new musl patches from gcc-6 (in development) to
gcc-5.1.0.
=> gcc/patches: Add musl patches to gcc 5.1.0

patches/newlib/1.20.0/110-fix-eabihf.patch
This patch gets newlib 1.20.0 to work with eabihf tuple.
This commit closes #23
=> newlib/patch: Add eabihf patch

scripts/build/cc/100-gcc.sh
This option is old. GCC 4.3.x old. It isn't supported anymore, and just
confuses me. I'm not planning to support 4.3.x, or really anything older
then 4.7. So this option is gone to the wind.
=> gcc: Remove --enable-c99

config/target.in
Normally, a specific CPU fully implies the architecture level. For
example, a cortec-a8 is forcibly an armv7, so spwecifying both is
redundant, and even dangerous (as incompatible values may be passed).
So far, gcc was pretty happy when both were specified at the same time,
and some time ago, it started being a warning, and only recently was it
turned into a hard error.
So, hide the architecture level prompt when a CPU has been specified.
Signed-off-by: "Yann E. MORIN" <yann.morin.1998@free.fr>
=> arch: do not allow specifying both --with-arch and --with-cpu

config/target.in
Similarly to what we've just done to prevent both --with-arch and
--with-cpu, we do the same to prevent using both --with-cpu and
--with-tune at the same time, since --with-cpu should fully imply
the CPU to tune for (and gcc now errors out when both are specified.
Signed-off-by: "Yann E. MORIN" <yann.morin.1998@free.fr>
Cc: Bryan Hundven <bryanhundven@gmail.com>
=> arch: do not allow specifying both --with-cpu and --with-tune

contrib/gcc-test-suite/Makefile
The missing definition of $tmpdir caused it to default to /tmp, which
may cause problems when testcases generate temporary files in the
current directory ($TOPDIR) and then try to access them at $tmpdir.
Errors such as the following were reported in test-suite runs for both
arm and powerpc toolchains due to $tmpdir pointing to /tmp and files
being generated in $TOPDIR:
error: could not open dump file '/tmp/dump1/dump-noaddr.c.011t.cfg':
No such file or directory
FAIL: gcc.c-torture/unsorted/dump-noaddr.c,  -O0   -dumpbase
dump1/dump-noaddr.c -DMASK=1 -x c --param ggc-min-heapsize=1
-fdump-ipa-all -fdump-rtl-all -fdump-tree-all -fdump-noaddr
FAIL: gcc.dg/tree-prof/ic-misattribution-1.c execution:
file ic-misattribution-1.gcda does not exist,  -fprofile-generate
-D_PROFILE_GENERATE …
=> test-suite: define $tmpdir to $TOPDIR

configure.ac
Due to patch 0e45cdf, the VERSION string has changed. And so, the the sub
directory names has changed too:
From 'ct-ng.1.21.0' to 'ct-ng.crosstool-ng-1.21.0-xx-yyyyyyy'
This patch rename the sub directory to: 'crosstool-ng-1.21.0-xx-yyyyyyy'
Signed-off-by: Jean-Marie Lemetayer <jeanmarie.lemetayer@gmail.com>
=> autoconf: Update sub directory name

config/cc/gcc.in
This commit adds gcc 4.8.5 and 4.9.3.
Release notes can be found in these urls:
https://gcc.gnu.org/gcc-4.8/
https://gcc.gnu.org/gcc-4.9/
=> config: Add new gcc stable versions

patches/glibc/2.11/920-make-40.patch
Similar patch in http://colocsbar.blogspot.fr/2014/01/crosstool-ng-1190-et-make-40.html
=> Patch glibc 2.11's configure script to support Make 4

config/arch/avr.in, config/kernel/linux.in, config/libc/avr-libc.in, config/libc/avr-libc.in.2, config/target.in, config/toolchain.in, patches/binutils/2.25/avr/0001-AVR-only-support-C-for-AVR-memory-usage.patch, samples/avr/crosstool.config, samples/avr/reported.by, scripts/build/arch/avr.sh, scripts/build/libc/avr-libc.sh, scripts/build/libc/glibc.sh, scripts/build/libc/mingw.sh, scripts/build/libc/musl.sh, scripts/build/libc/newlib.sh, scripts/build/libc/none.sh, scripts/build/libc/uClibc.sh, scripts/functions, steps.mk
This patch series adds support for AVR avr-libc toolchains.
It is broken in a patch to add the AVR architecture and first 8-bit options,
followed by adding avr-libc as a C library option, then an avr target sample
and finally some other minor issues observed during testing.
Initially this was tested by adding a lot of other configuration options by
taking the Arch Linux recipes as a reference. They can be found in:
https://projects.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/avr-binutils
https://projects.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/avr-gcc
https://projects.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/avr-libc
Trying to make crosstool-ng equivalent to these options would require a lot of
changes to …
=> avr: add support for AVR avr-libc toolchains

patches/gcc/4.5.3/120-siginfo.patch
I was attempting to build a gcc-4.5.3 toolchain for MIPS; this changeset fixed the problem I encountered in  the 'final gcc' stage: struct siginfo was an incomplete type.
=> fix linux-unwind.h siginfo incomplete type

config/companion_libs/isl.in, scripts/build/companion_libs/121-isl.sh
Fix for issue #141 Unknown configure options for lib ISL:
Added new config ISL_V_0_14_or_later and ISL_V_0_12_or_later to select
proper configure options for isl 0.14.x and 0.12.x in 121-isl.sh.
=> Added new config ISL_V_0_14_or_later and ISL_V_0_12_or_later to select

scripts/build/cc/100-gcc.sh
Configure for core GCC did not use Core gcc extra config.
Use now config variable CT_CC_GCC_CORE_EXTRA_CONFIG_ARRAY.
=> Fix for issue #142:

config/libc/glibc.in
* Add glibc 2.22
* Add a constraint on glibc-2.21 that depends on gcc-4.6 or greater.
See: https://sourceware.org/ml/libc-alpha/2015-02/msg00119.html
======================================================================
* The minimum GCC version that can be used to build this version of
the GNU C Library is GCC 4.6.  Older GCC versions, and non-GNU
compilers, can still be used to compile programs using the GNU C
Library.
======================================================================
=> glibc: Add 2.22, and add a constraint on glibc >= 2.21

config/libc/glibc.in, scripts/build/libc/glibc.sh
glibc-2.17 and above no longer have external addons or ports.
So if we are => 2.17, don't even think about trying to mess with ports
or addons.
=> glibc: Fix applying addons to glibc => 2.17

config/companion_libs/cloog.in, config/companion_libs/isl.in
Adding isl 0.15.
Added following constrains:
isl 0.14 and 0.15 require  CLooG 0.18.4 or later.
isl 0.11.1 and 0.12.2 require CLoog older than 0.18.4.
=> Adding CLooG/isl constraint

config/binutils/binutils.in, patches/binutils/2.25.1/120-sh-conf.patch, patches/binutils/2.25.1/300-001_ld_makefile_patch.patch, patches/binutils/2.25.1/300-012_check_ldrunpath_length.patch, patches/binutils/2.25.1/avr/0001-AVR-only-support-C-for-AVR-memory-usage.patch
Adding patches for binutils version 2.25.1 as copy of 2.25.
Support binutils 2.25.1 in configuration.
Note: The patches do apply, but I didn't check the resulting tools.
=> Support binutils V 2.25.1

config/cc/gcc.in.2, config/libc.in
Enable definition of "Use __cxa_atexit" for bare-metal systems, if the used
libc does provide such a function. The libc configuration have to select
LIBC_PROVIDES_CXA_ATEXIT.
=> Fix for issue #147:

config/cc/gcc.in
CC_GCC_CUSTOM is no longer part of the gcc version choice, but an independent
configuration to enable CC_GCC_CUSTOM_LOCATION.
=> Remove CC_GCC_CUSTOM from the version choice

config/libc/newlib.in
LIBC_NEWLIB_CUSTOM is no longer part of the newlib version choice, but an
independent configuration to enable LIBC_NEWLIB_CUSTOM.
All newlib versions >=2.0.0 does provide __cxa_atexit. To enable this function
in GCC, all versions >=2.0.0 does now select LIBC_PROVIDES_CXA_ATEXIT.
Note: The patch for issue #147 needs to be applied for a working
"ct-ng menuconfig" execution!
=> Remove LIBC_NEWLIB_CUSTOM from the version choice

config/binutils/binutils.in
BINUTILS_CUSTOM is no longer part of the binutils version choice, but an
independent configuration to enable BINUTILS_CUSTOM.
=> Remove BINUTILS_CUSTOM from the version choice

config/global.in
After the Kconfig update (Issue "Update kconfig version" #127) tristate Kconfig configuration options can be set only to enabled ("y") or disabled ("n"). Tristates can not be set to module ("m") any more.
See for example "C compiler / Use sjlj for exceptions", which is no longer a tristate option.
Fix: The "option modules" setting must be set on the MODULES configuration option to enable tristates again.
Signed-off-by: Philipp Kirchhofer <philipp@familie-kirchhofer.de>
=> Fix tristate Kconfig options

config/companion_libs/isl.in
gcc 5.x   -> isl 0.12.2, 0.14 0.15
gcc < 5.x -> cloog < 0.18.4  -> isl 0.12.2, 0.11.1
-> cloog >= 0.18.4 -> isl 0.14
=> Fixed issue 173 and 174.

patches/glibc/2.17/100-Fix-ARM-build-with-GCC-trunk.patch
When building a toolchain with glibc <= 2.19 and gcc >= 5.1 the build fails with message
```
In function _Unwind_Resume: undefined reference to libgcc_s_resume
```
This commit backports a fix from glibc 2.20.
The fix may be applied to all glibc versions <= 2.19, but I did test only with glibc 2.17, where it works fine now.
=> Fix building glibc 2.17 with gcc 5.1+

config/companion_libs/isl.in
Remove isl 0.15, because it will not compile with gcc 5.2.0 without patching gcc.
=> Remove isl 0.15

scripts/build/cc/100-gcc.sh
Removed doubled setting of --disable-libmudflap in do_gcc_core_backend.
=> Doubled setting of --disable-libmudflap removed.

.travis.yml
Set language to 'bash' to get rid of interfering environment variable CC=gcc.
=> Fixed travis-ci environment setting

Makefile.in, config/global/logging.in, configure.ac
This commit introduces a configure time option to let the build know
that this is going to be an automated build.
This forces the build to disable the progress bar, log tool warnings,
and force the log level to debug.
=> configure: Add automated build option

config/global/logging.in
I forgot that the logs must stay small, and if they fail we'll grab the
last few hundered lines.
Note, the logs must stay smaller then 4M.
=> config: Tone down automated build logs

scripts/build/cc/100-gcc.sh
Adding missing if/else blocks in do_gcc_core_backend for CT_CC_GCC_LIBSSP,
CT_CC_GCC_HAS_LIBQUADMATH and CT_CC_GCC_LIBQUADMATH (--en/disable-libssp,
--en/disable-libquadmath, --en/disable-libquadmath-support) from function
do_gcc_backend.
=> Adding missing if/else blocks in do_gcc_core_backend.

config/cc/gcc.in.2, scripts/build/cc/100-gcc.sh
Add additional environment variables for gcc build (make) with new option
GCC_EXTRA_ENV_ARRAY.
=> Add additional environment variables for gcc build.

scripts/build/cc/100-gcc.sh
Synchronize CT_CC_GCC_USE_LTO parameter setting in do_gcc_backend with the one
from do_gcc_core_backend, by adding "--enable-lto"/"--disable-lto".
Signed-off-by: Jasmin Jessich <jasmin@anw.
=> Synchronize CC_GCC_USE_LTO parameter setting II

config/cc/gcc.in.2, scripts/build/cc/100-gcc.sh
Using "all" and "install" targets in do_gcc_core_backend if configured
- New configurations:
- CC_GCC_TARGET_FINAL:
Use the default targets "all" and "install" for the final compiler for
bare metal.
- Adding parameter "build_step" to function do_gcc_core_backend:
do_gcc_core_backend is used for the core compiler and in case of bare metal
for the final compiler, too. To have better control over the parameters for
the final compiler "build_step" is used.
- Used for proper logging.
- Use CT_CC_GCC_CORE_EXTRA_CONFIG_ARRAY or CT_CC_GCC_EXTRA_CONFIG_ARRAY.
- If CT_CC_GCC_TARGET_FINAL is set and the final compiler is build then the
make targets for the final compiler are used ("all", "install").
=> Using "all" and "install" targets in do_gcc_core_backend if configured

docs/3 - Configuring a toolchain.txt
=> Fix a typo in the documentation

config/binutils/binutils.in
The gold linker cannot currently be built in a static toolchain build.
This may get fixed in a future version of crosstool-NG.
Also, there is a bit of weirdness here. versions of binutils >= 2.21
have GOLD (BINUTILS_HAS_GOLD), but that doesn't mean it should be used.
For instance, if the architecture is not supported.
So with that, we create a new hidden option: BINUTILS_GOLD_SUPPORT
Which in turn depends on BINUTILS_GOLD_SUPPORTS_ARCH, BINUTILS_HAS_GOLD,
and not STATIC_TOOLCHAIN... then replace anything that previously
depended on BINUTILS_HAS_GOLD with our new BINUTILS_GOLD_SUPPORT option.
This closes #210
=> binutils: Gold conflicts with Static Toolchain

config/arch/mips.in
This is a weird artifact from when mips64 was first introduced to ct-ng
and was never removed from experimental.
If you have problems building a mips64 toolchain, please report on the
mailing list or on github issues.
=> config: MIPS64 is no longer experimental

scripts/build/kernel/linux.sh, scripts/build/libc/uClibc.sh
While debugging new support for uClibc-ng, I noticed issues with not yet supported arc, and blackfin architectures.
* Linux needs CROSS_COMPILE set during the install/check headers step, as some architectures (notably arc and blackfin) set a default CROSS_COMPILE if it is not set.
* uClibc build script was using a "compat" command line argument, but we should use CROSS_COMPILE instead of CROSS to define our cross compiler.
=> Fix some cross_compile issues

ct-ng.in, samples/samples.mk, scripts/crosstool-NG.sh.in
Add `ct-ng source` to just fetch the sources and stop (without the need to change options in .config).
=> ctng source

patches/uClibc/0.9.33.2/200-fix-kernel-3.4plus-build.patch
Commit 1a25115a1851d3defdf4d37825d8a291be078e53 deleted non-GCC related
files, including the patch for uClibc to compile with Linux kernels after
3.4.
uClibc 0.9.30 patches are not restored by this change (0.9.30 is broken
with recent kernels for multiple other breakages in addition to that; if
not retired, it needs to be fixed properly).
=> Restore uClibc-based samples.

scripts/build/companion_libs/110-mpfr.sh
mpfr.org has been less then reliable, so lets make gnu.org the primary
instead of the secondary source.
This closes #250
=> mpfr: Swap primary mirror to gnu.org

config/global/paths.in, scripts/build/cc/100-gcc.sh, scripts/build/internals.sh, scripts/crosstool-NG.sh.in
Starting from GCC 4.6 there is an install-strip target in Makefile which is provided for stripping GCC executables and libraries. The most important for me is that this option allows to strip libstdc++.a so that I can use static libcstdc++ without debugging symbols.
=> Use install-strip target for gcc optionally

.travis.yml, config/arch/xtensa.in, config/arch/xtensa.in.2, patches/binutils/2.25.1/905-Fix-trampolines-search-code-for-conditional-branches.patch, patches/binutils/2.25.1/906-xtensa-optimize-check_section_ebb_pcrels_fit.patch, patches/binutils/2.25.1/907-xtensa-optimize-removed_by_actions.patch, patches/binutils/2.25.1/908-xtensa-optimize-find_removed_literal.patch, patches/binutils/2.25.1/909-xtensa-replace-action-list-with-splay-tree.patch, patches/binutils/2.25.1/910-xtensa-optimize-trampolines-relaxation.patch, patches/binutils/2.25.1/911-xtensa-fix-localized-symbol-refcounting-with-gc-sect.patch, patches/binutils/2.25.1/912-xtensa-fix-gas-segfault-with-text-section-literals.patch, patches/binutils/2.25.1/913-xtensa-add-auto-litpools-option.patch, patches/gcc/5.2.0/110-xtensa-implement-trap-pattern.patch, patches/gdb/7.10/110-xtensa-initialize-call_abi-in-xtensa_tdep.patch, patches/gdb/7.10/111-xtensa-make-sure-ar_base-is-initialized.patch, patches/gdb/7.10/112-WIP-end-of-prologue-detection-hack.patch, samples/xtensa-unknown-linux-uclibc/crosstool.config, samples/xtensa-unknown-linux-uclibc/reported.by, scripts/build/arch/xtensa.sh, scripts/build/binutils/binutils.sh, scripts/build/cc/100-gcc.sh, scripts/build/debug/300-gdb.sh, scripts/build/libc/newlib.sh
Hi Bryan,
this series adds support for Xtensa architecture to crosstool-NG (issue #243).
There are architecture-specific patches for the latest binutils, gcc and gdb.
Patch for the newlib is not ready for mainline and needs more work.
Please let me know what you think.
=> Add support for Xtensa architecture

configure.ac
While usually distributed with ncurses, some distributions distribute
this library separately. Check to make sure it is installed.
This closes #241
=> configure: Check for libtinfo.so

configure.ac
We require GNU/patch, and when we install patch with `pkg`, crosstool-ng
still only finds the BSD/patch in /usr/bin/patch.
This commit fixes that and searches for gpatch first.
=> configure: fix search for gpatch for FreeBSD

configure.ac, kconfig/Makefile
I previously thought that tinfo could only be a link to libncurses in
modern ncurses installations. I was wrong.
Now we check for ncurses, then check for tinfo. If tinfo is a link to
ncurses, it is then not required to link against. But if libtinfo is
providing tgetent, and not libncurses, then we must add it to LIBS as
well.
Also, kconfig shouldn't hardcode -lncurses, it should use what is in
$(LIBS).
=> configure: Correctly search for tinfo for kconfig

config/libc/uClibc.in
In commit c9704c6683ee2ddab8be390f48f6c2de412b80dc, I forgot to bump the
version in the prompt for uClibc-ng-1.0.9.
Reported-by: Reinoud Koornstra <reinoudkoornstra@gmail.com>
=> uClibc-ng: Fix version prompt

scripts/showSamples.sh
I'm not even sure how the previous loop was supposed to work.
The config variables are not exported to the environment.
Now we properly get which cc we are using and grab the version to
display it correctly with the output of wiki-samples.
=> showSamples.sh: Fix how we get gcc and version for showSamples.sh

scripts/showSamples.sh
Some LIBCs need some love in showSamples.sh.
uClibc-ng is of type of uClibc, so output uClibc-ng if
CT_LIBC_UCLIBC_NG=y.
mingw-w64 doesn't have a CT_LIBC_VERSION, but it does have a
CT_WINAPI_VERSION. So output that instead.
=> showSamples: Fix uClibc-ng name and Mingw-w64 versions

config/arch/xtensa.in, config/arch/xtensa.in.2, docs/C - Misc. tutorials.txt
Hi Bryan,
this series fixes inconsistencies in xtensa kconfig entries and help text and adds section "Using crosstool-NG to build Xtensa toolchains" to misc. tutorials as requested in issue #241.
=> Xtensa docs update

Makefile.in
`make uninstall` is ran against `$(TARGETS)`, which includes `lib-kconfig`.
`lib-kconfig` is installed as a part of the `lib` target, so during
uninstall, removing `lib` is enough to also remove `lib-kconfig`.
Filter out `lib-kconfig` during `real-uninstall`.
=> Makefile.in: Fix uninstall target

scripts/build/libc/uClibc.sh
As per the change notes of GCC-6:
https://gcc.gnu.org/gcc-6/changes.html
and conversations I've had with the buildroot folks, there is no need
to support sh5/sh64.
=> uClibc: remove references to sh64*

patches/binutils/2.25.1/340-Darwin-gold-binary-cc-include-string-not-cstring.patch, patches/binutils/2.25.1/350-Darwin-Two-fixes-from-Android-NDK-PTHREAD_ONCE_INIT-wcsncasecmp.patch, patches/binutils/2.25/340-Darwin-gold-binary-cc-include-string-not-cstring.patch, patches/binutils/2.25/350-Darwin-Two-fixes-from-Android-NDK-PTHREAD_ONCE_INIT-wcsncasecmp.patch, scripts/build/cc/100-gcc.sh
One of the patches came from Google's Android NDK and I kept it as it was for credit and origin tracing purposes.
=> Fixes binutils and gold (raspi2 sample builds ok if you disable the static toolchain options)

config/libc/uClibc.in.2, scripts/build/libc/uClibc.sh
This commit adds a kconfig option to enable IPv6 support.
=> uClibc: Add kconfig option to enable IPv6 support

scripts/build/binutils/binutils.sh, scripts/build/debug/300-gdb.sh
When building from:
{git,http}://sourceware.org/git/binutils-gdb.git
and setting BINUTILS_CUSTOM or GDB_CUSTOM, they could be the same
source.
These config options should not affect normal released versions.
=> binutils/gdb: Fix configure options when building from binutils-gdb repo

patches/binutils/2.25.1/400-arm-rotate_left-fix.patch
https://sourceware.org/bugzilla/show_bug.cgi?id=19281
=> binutils: add patch that fixes mac os x gold build

scripts/build/binutils/binutils.sh
In commit: 74d555b2
A regex in a parameter subsitution replaces a '#' hash symbol, but it is
not made literal '\#', so from the hash to the end of the line is a
comment.
=> binutils: Fix binutils manuals_install variable

scripts/build/binutils/binutils.sh
If building a static toolchain, the ldflags option passed to
do_binutils_backend is overridden when we set `LDFLAGS=-all-static`.
We should pass `LDFLAGS=${ldflags} -all-static` in this case.
This fixes #297
=> binutils: Fix LDFLAGS for static toolchain

scripts/build/binutils/binutils.sh
If CT_BINUTILS_FOR_TARGET_IBERTY is set, then it seems that we also must
set `--enable-install-libiberty` for configure to pickup that it needs
to be installed.
This closes #302
=> binutils: Fix installing libiberty for target

config/cc/gcc.in, scripts/build/cc/100-gcc.sh
These commits update the download path for new linaro releases, and adds a new 5.2-2015.11 release.
=> Update gcc linaro

config/kernel/linux.in
The following versions were updated:
* 4.3       -> 4.3.3 (stable)
* 4.2.6     -> 4.2.8 (EOL)
* 4.1.13    -> 4.1.15
* 3.18.24   -> 3.18.25
* 3.14.57   -> 3.14.58
* 3.12.50   -> 3.12.51
* 3.10.93   -> 3.10.94
* 3.2.72    -> 3.2.75
* 2.6.32.68 -> 2.6.32.69
4.3 mainline is now 4.3.3 stable
The 4.2 series is now EOL. You should move to 4.3.3!
=> linux: Update kernel versions

patches/gcc/5.3.0/370-gcc-plugin-Win-Dont-need-undefined-extern-var-refs-nor-fpic.patch, patches/gcc/5.3.0/380-gcc-plugin-POSIX-include-sys-select-h.patch, scripts/build/companion_libs/200-libelf.sh, scripts/build/companion_libs/210-expat.sh, scripts/build/companion_libs/320-libiconv.sh
Fixes https://sourceware.org/ml/crossgcc/2015-11/msg00084.html (expat-for-host library nature (static/shared) to match with the other host libraries; it's linked to gettext and they aren't allowed to differ), then some follow on bugs I encountered trying to build that sample (patches were needed so that GCC plugins can be built on Cygwin). I've yet to verify that it builds completely yet, so this is more for discussion and so I can get testing feedback from Thies Peter, so don't merge yet, even if everything  looks good (which I doubt).
Cheers!
=> Cygwin more fixes

scripts/build/cc/100-gcc.sh
The two gcc backend functions are getting very close to being duplicated
code. To help in the process of merging the two backends, this change
syncronizes the two functions so they are easier to diff.
This commit has no functional changes.
=> gcc: Sync backend functions

config/cc/gcc.in.2, scripts/build/cc/100-gcc.sh
I was noticing that $extra_user_env was inconsistently used in
100-gcc.sh. I don't feel comfortable having just any make flag or
environment variable passed to make from a config file. If a specific
option needs to be passed to make for gcc, then a specific kconfig
option should be added for that make flag/option/env.
=> gcc: remove CC_GCC_EXTRA_ENV_ARRAY

scripts/build/cc/100-gcc.sh
When creating a baremetal toolchain, CC_GCC_ENABLE_CXX_FLAGS has no
effect. This closes #298
=> gcc: Fix CC_GCC_ENABLE_CXX_FLAGS for mode=baremetal

scripts/build/cc/100-gcc.sh
In a5057713a0394d189adc8b9abb0eb65592ecfc49
...I forgot to add a line continuation at the break in the 'if'
statement.
Reported-by: asavah <asavah@avh.od.ua>
=> gcc: fix previous commit

patches/binutils/2.25.1/350-Darwin-Two-fixes-from-Android-NDK-PTHREAD_ONCE_INIT-wcsncasecmp.patch
OSX SDK has a declaration for `wcsncasecmp` since 10.7, which conflicts with
the definition provided by the patch for binutils.
In `/usr/include/wchar.h` on ElCapitan we have:
```c
/* Additional functionality provided by:
* POSIX.1-2008
*/
#if __DARWIN_C_LEVEL >= 200809L
__BEGIN_DECLS
// [snip]
int     wcsncasecmp(const wchar_t *, const wchar_t *, size_t n) __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_4_3);
// [snip]
__END_DECLS
#endif /* __DARWIN_C_LEVEL >= 200809L */
```
=> patches/binutils: wcsncasecmp is provided by OSX >= 10.7

patches/binutils/2.23.2/914-xtensa-fix-signedness-of-gas-relocations.patch, patches/binutils/2.24/914-xtensa-fix-signedness-of-gas-relocations.patch, patches/binutils/2.25.1/914-xtensa-fix-signedness-of-gas-relocations.patch, patches/binutils/2.26/914-xtensa-fix-signedness-of-gas-relocations.patch
Hi Bryan,
this is a backport of a fix for xtensa gas recently committed to binutils.
It fixes failure to assemble certain range of line numbers debug info.
=> binutils: fix .loc handling in xtensa gas

config/cc/gcc.in, scripts/build/cc/100-gcc.sh
As crosstools-ng only support GCC >= 4.8 we do not need libelf for gcc. GCC dropped this dependency with 4.6.
Signed-off-by: Matthias Weisser <m.weisser.m@gmail.com>
=> Remove GCC dependency to libelf

scripts/functions
Hardlinking the custom source directory does not work across separate
mount points. Chnage this to a softlink instead.
This closes #336
Reported-by: Jasmin Jessich <jasmin@anw.at>
=> functions: Softlink custom directory

patches/binutils/2.23.2/915-xtensa-fix-.init-.fini-literals-moving.patch, patches/binutils/2.24/915-xtensa-fix-.init-.fini-literals-moving.patch, patches/binutils/2.25.1/915-xtensa-fix-.init-.fini-literals-moving.patch, patches/binutils/2.26/915-xtensa-fix-.init-.fini-literals-moving.patch
Hi Bryan,
this is a backport of a fix for xtensa gas recently committed to binutils.
It fixes build errors seen with projects that have .init/.fini sections and use text-section-literals.
=> binutils: fix .init/.fini literals moving in xtensa gas

scripts/functions
I should have just used ln -sf when I rewrote the custom locations
change. BSD based systems don't have 'cp -s', so switch to using 'ln
-sf'.
=> functions: use 'ln -sf' for softlinks

config/cc/gcc.in.2, config/debug/gdb.in.cross, config/debug/gdb.in.gdbserver, config/debug/gdb.in.native, config/toolchain.in, configure.ac
This is a semi-nasty-hack to see if gcc can static link.
Obviously on Mac OS X this is not possible, so we set
CT_CONFIGURE_has_static_link=y if it can.
=> configure: Check to see if gcc can static link

scripts/build/libc/musl.sh
This commit moves the do_libc_configure function to do_libc_backend and
switches do_libc_start_files and do_libc_final to call do_libc_backend.
The major reason for the rewrite is that musl => 1.1.13 has had it's own
build system rewritten and can now build out-of-tree.
=> musl-libc: Rewrite musl.sh build script

configure.ac
Because I don't pass `-o` to gcc, it makes an a.out file with gcc.
For clang it doesn't make the a.out, as that is not the default.
It doesn't hurt to output to /dev/null for both.
=> configure: Don't write a.out on static compiler check

patches/gcc/4.8.5/130-pr43538.patch, patches/gcc/4.8.5/131-mt-ospace-preserve-FLAGS_FOR_TARGET.patch, patches/gcc/4.9.3/130-pr43538.patch, patches/gcc/4.9.3/131-mt-ospace-preserve-FLAGS_FOR_TARGET.patch, scripts/build/cc/100-gcc.sh
Hi Bryan,
this series makes it possible to build libstdc++ for baremetal cross-compiler with flags specified in the CT_TARGET_CFLAGS. It backports two gcc fixes that preserve CFLAGS_FOR_TARGET and CXXFLAGS_FOR_TARGET from gcc-5.x to gcc-4.8.x and gcc-4.9.x and passes these environment variables to gcc configure script in do_gcc_core_backend() as it is done in do_gcc_backend().
It fixes issue #374.
=> Pass CFLAGS_FOR_TARGET/CXXFLAGS_FOR_TARGET for libstdc++ in baremetal build

patches/glibc/2.22/120-cve-2105-7547-getaddrinfo-stack.patch
This resolves a vulnerability related to getaddrinfo().
=> Add patch for glibc 2.22 for CVE-2015-7547.

scripts/addToolVersion.sh
This issue was reported on github:
https://github.com/crosstool-ng/crosstool-ng/issues/378
by: alonbg
This is the same addToolVersion.sh change in the zipfile, with minor
changes. (whitespace)
This closes #378
=> addToolVersion: Fix syntax issues

patches/gcc/5.3.0/130-build_gcc-5_with_gcc-6.patch
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69959
...was observed while trying to build gcc-5.3.0 on latest (at the time
of this change) archlinux using gcc-6.1.1.
This patch fixes the issue.
=> patches/gcc: Backport fix for building gcc-5 with gcc-6

config/binutils/binutils.in.2, scripts/build/binutils/binutils.sh
The elf2flt git repository has been moved to GitHub. Updated the script
accordingly.
Signed-off-by: Martin Lund <martin.lund@keep-it-simple.com>
=> Update elf2flt git repository location

scripts/functions
It must be "DEBUG", not "Debug"
Signed-off-by: Carlos Santos <casantos@datacom.ind.br>
=> scripts/functions: fix log level in call to CT_DoLog

scripts/crosstool-NG.sh.in
For a cross-compiler, we only need to make the 'build tools' for the
'build'. We also build the 'build tools' for the 'host' when building a
cross-canadian toolchain.
Closes #430
=> cross: Only make 'build tools' for the 'build'

scripts/build/libc/uClibc.sh
Build and install shared libs only if requested, i.e. CT_SHARED_LIBS=y. Without this patch sysroot was always populated with shared libs.
Install native ldd and ldconfig utils to sysroot.
=> uClibc: improve managing shared libs

scripts/build/internals.sh
On mingw target gdbserver is suffixed with '.exe', thus
plain 'strip gdbserver' fails.
Signed-off-by: Kirill K. Smirnov <kirill.k.smirnov@gmail.com>
=> internals: properly strip gdbserver

config/debug/duma.in
Add SHARED_LIBRARY dependency to DUMA shared library option, partially fixes #440
=> duma: add SHARED_LIBS dependency for DUMA shared library option

scripts/build/binutils/binutils.sh
On the stage "core gcc pass-2" the following layout is created:
1) buildtools/bin/TARGET-{ar,as,elf2flt,flthdr,ld,ld.bfd,ranlib,strip}
2) buildtools/TARGET/bin/{ar,as,elf2flt,flthdr,ld,ld.bfd,ranlib,strip}
3) x-tools/TARGET/bin/TARGET-{ar,as,elf2flt,flthdr,ld,ld.bfd,ranlib,strip}
4) x-tools/TARGET/TARGET/bin{ar,as,elf2flt,flthdr,ld,ld.bfd,ranlib,strip}
where both (1) and (2) are symlinks to (3). This inconsistent and effectively
renders core pass-2 gcc with elf2flt linker unusable. Make (1) links point to (3)
and (2) links point to (4).
Related elf2flt discussion:
https://github.com/uclinux-dev/elf2flt/pull/4
Signed-off-by: Kirill K. Smirnov <kirill.k.smirnov@gmail.com>
=> binutils: make symlinks in a consistent way

scripts/build/binutils/binutils.sh
elf2flt is configured with -Werror flag by default. Disable it.
Signed-off-by: Kirill K. Smirnov <kirill.k.smirnov@gmail.com>
=> elf2flt: do not treat warnings as errors

scripts/build/cc/100-gcc.sh
After building final gcc, place the libraries in non-sysroot libs
into sysroot.
=> Fix issue #449.

config/cc/gcc.in, config/cc/gcc.in.2, scripts/build/cc/100-gcc.sh
GCC 6.1.0 (final compiler) fails to compile against musl.
=> Disable libmpx in x86-musl.

patches/glibc/2.16.0/510-accept-make-versions-4.0-or-higher.patch, patches/glibc/2.16.0/520-fix-sed-configure-check.patch
As suggested in  #339 this is targeting the 1.22 branch.
These are some back ports that allow glibc-2.16.0 to build on a newer system.
=> Glibc 2.16.0 backports for 1.22

patches/gcc/4.9.3/120-gcc-config.gcc-fix-typo-for-powerpc-e6500-cpu_is_64b.patch
This resolves crosstool-ng/crosstool-ng#405
=> Apply patch for config.gcc to support e6500 to gcc4.9.3

scripts/build/binutils/binutils.sh
Reverts crosstool-ng/crosstool-ng#454
Warnings for elf2flt should be reported upstream!
=> Revert "elf2flt: do not treat warnings as errors"

patches/ltrace/0.7.3/008-glibc-2.24.patch
GLIBC 2.24 declared readdir_r as deprecated and suggests to use readdir.
uClibc-ng's readdir is thread-safe as well.
=> Fix ltrace under glibc 2.24.

patches/gcc/5.4.0/878-xtensa-Fix-PR-target-78603.patch, patches/gcc/6.2.0/872-xtensa-Fix-PR-target-78603.patch
Hello,
please pull the fix for xtensa PR target/78603 backported to gcc 5.x and 6.x.
=> gcc: backport fix for xtensa PR target/78603

scripts/build/companion_libs/200-libelf.sh, scripts/build/companion_libs/210-expat.sh, scripts/build/companion_libs/220-ncurses.sh, scripts/build/debug/300-gdb.sh
This patch fixes libexpat detection for gdb-native and
gdb-cross static builds.
For gdb-native build configure should not touch system
/usr/{lib,include} directories while looking for libexpat.
To fix this we pass --without-libexpat-prefix flag
to configure script.
For gdb-cross build configure is allowed to investigate
system /usr/{lib,include} directories, but it does not
hurt to disable this behavior. In this case configure
falls back to -lexpat, which works as expected.
For more info:
http://marc.info/?l=gnulib-bug&m=129660262901148&w=2
Signed-off-by: Kirill Smirnov kirill.k.smirnov@gmail.com
=> debug/gdb: properly link with expat

config/libc/uClibc.in
Retire 1.0.{17,18,19}. Both static link & dlopen issues are now
apparently fixed.
=> Add uclibc-ng 1.0.20.

patches/gcc/4.8.5/132-build_gcc-5_with_gcc-6.patch
4.9.4 doesn't need this, fixed upstream.
=> Backport the fix to 4.8.5.

.travis.yml, patches/uClibc-ng/1.0.20/100-xtensa-static-link.patch
uClibc-ng 1.0.20 fixed static linking with "libdl" by adding all libdl functions
into the libc. On xtensa, though, libdl contains an unresolved reference that is
satisfied by the ld.so - which is not a part of the linking in a static case.
=> Fix xtensa static link.

scripts/functions
Some errors from make(1) do not include a file reference in brackets.
=> Catch more make errors.

config/global/paths.in, scripts/crosstool-NG.sh.in
We now use CT_PREFIX and expect the resulting toolchain to be relocatable.
=> Kill CT_INSTALL_DIR.

ct-ng.in
If configured with --enable-local, CT_NG is exported as plain 'ct-ng'
without any path. showSamples.sh then fails to invoke ct-ng (as current
directory is not in $PATH).
=> Fix ct-ng show-config.

config/toolchain.in, scripts/build/cc/100-gcc.sh, scripts/build/libc/newlib.sh
This is caused by doing "cp <src-dir>/include <dst-dir>/include" twice. First it creates <dst-dir>/include, second time it creates <dst-dir>/include/include.
On top of that, it turned out that newlib samples copied headers into both <sysroot>/usr/include and <prefix>/<target>/include. The former is not needed for bare metal, as there is no system root FS to speak of. Moreover, installing newlib into sysroot does not work, as it does not handle "install_root" variable.
Hope this untangles the current mess a bit.
=> Avoid creating include/include

scripts/build/cc/100-gcc.sh
Only needed in canadian configurations to build libstdc++ (broken by removal of include/include headers)
=> Restore copying headers for gcc_build

patches/glibc/2.23/910-typedef-caddr.patch
This is essentially the same pull-request as "canadian build: fix mingw32". This only applies to glibc-2.23.
=> Fix for Candian-Cross builds for mingw host to arm target.

patches/glibc/2.20/910-typedef-caddr.patch, patches/glibc/2.21/910-typedef-caddr.patch, patches/glibc/2.22/910-typedef-caddr.patch, patches/glibc/2.24/910-typedef-caddr.patch
... 2.20, 2.21, 2.22 and 2.24.
=> Propagate caddr_t patch to other glibc versions

patches/gcc/6.3.0/900-libgfortran-missing-include.patch
When building a mingw toolchain with fortran enabled as a language for gcc the build fails due to an implicit declaration of free caused by a missing include in combination with the werror=implicit-function-declaration compilation flag.
This patch adds the missing include
=> Gcc compilation fix when fortran is enabled

config/libc/mingw.in, scripts/build/libc/mingw.sh
There are some useful tools (widl, gendef ...) provided by mingw-w64
and do not waste the developers' works.
=> mingw: compile the mingw-w64 companion tools as well

config/backend.in, docs/0 - Table of content.txt, docs/3 - Configuring a toolchain.txt
I don't see what CT_BACKEND adds to configurability of crosstool-ng; apparently, it just increases the number of combinations to be tested (and I don't think we've tested it in a while). If you use it, please tell me what is the value of this option. Otherwise, I plan to obsolete it in the next release and retire it afterwards.
=> Declare BACKEND obsolete.

patches/glibc/2.23/120-Fix-build-with-enable-static-nss.patch, patches/glibc/2.24/120-Fix-build-with-enable-static-nss.patch
2.22 and older have more warnings that break the build.
=> Fix glibc 2.23/2.24 with --enable-static-nss.

configure.ac
=> Bump autoconf requirement to 2.65

config/debug/gdb.in.cross, config/debug/gdb.in.gdbserver
Also, do not select gdbserver for cross-gdb automatically, or it may
be selected even without meeting the dependencies (if C++ is not enabled)
=> Require C++ support for gdbserver 7.12 or newer

configure.ac
Recent GMP/GCC/GDB releases require c++.
=> Check for C++ in configure

config/companion_libs/ncurses.in, patches/ncurses/6.0/999-create-run_tic.patch, scripts/build/companion_libs/220-ncurses.sh
- Allow user to specify configure arguments to pass through to host/target
ncurses.
- Checkbox for --disable-database
- String option for --with-fallbacks
=> Allow some tunables for ncurses

config/target.in
... these are apparently not needed with the current kconfig and only
result in warnings like "SYMBOL changed state" and "reassigning SYMBOL".
Perhaps, it was necessary to run kconfig without first generating
config.gen? But now all the targets that invoke $(CONF) have
`config_files` as a dependency.
=> Remove "pre-declaration" of config options

config/debug/gdb.in.gdbserver, config/debug/gdb.in.native, scripts/build/debug/300-gdb.sh
... when building native GDB/gdbserver.
Suggested by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>
=> Supply --disable-build-with-cxx instead of requiring C++

Makefile.in, configure.ac, kconfig/Makefile, scripts/addToolVersion.sh, scripts/build/arch.sh, scripts/build/binutils/binutils.sh, scripts/build/cc/100-gcc.sh, scripts/build/debug/200-duma.sh, scripts/build/debug/300-gdb.sh, scripts/build/debug/duma.in, scripts/build/internals.sh, scripts/build/kernel/linux.sh, scripts/build/libc/glibc.sh, scripts/build/test_suite/gcc.sh, scripts/crosstool-NG.sh.in, scripts/functions, scripts/gen_in_frags.sh, scripts/patch-renumber.sh, scripts/populate.in, scripts/saveSample.sh.in, scripts/showSamples.sh, scripts/xldd.in
... and then use the right option. See the note in scripts/functions
on where we should use ${foo} and where just 'foo'; this boils down to
whether we can expect the build tools override to be in effect (e.g. in
the actual build scripts) or not (i.e. outside of scripts/build).
While running in scripts/functions, or in scripts/crosstool-NG.sh the
build tools override directory (.build/tools/bin) may have not been
set up (yet, or at all).
Also, modify the installed scripts (populate, xldd) accordingly.
=> Determine whether -E/-r option selects extended regexp

scripts/build/companion_libs/320-libiconv.sh, scripts/build/companion_libs/330-gettext.sh
Previous version by Ray Donnelly was skipping them for all *linux*.
This skips it for GLIBC only.
=> Skip gettext/libiconv on linux-gnu

config/libc/uClibc.in
The V={1,2} have opposite meaning in uClibc and uClibc-ng, reflect that.
=> Refine previous fix to uClibc verbosity setting

config/cc/gcc.in.2, scripts/build/cc/100-gcc.sh
Adding new tristate configuration for TLS (Thread Local Storage) to
add "--enable-tls" (y), "--disable-tls" (n) or nothing (m).
Signed-off-by: Jasmin Jessich jasmin@anw.at
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/crosstool-ng/crosstool-ng/375)
=> Added new gcc config option CC_GCC_CONFIG_TLS

patches/elf2flt/4820f0dbb77cd6564d5fa0817218fe2a1fb99f32/100-no-lcygwin.patch, scripts/build/binutils/binutils.sh
The -lcygwin -lc actually breaks the build: elf2flt picks up the symbols for getopt/optarg via
<getopt.h> in binutils-X.Y/include, where optarg is declared without dllimport attribute.
Therefore it pulls in getopt() from libc/libcygwin, but since optarg is not prefixed with
_imp__, it is pulled from libiberty. But the object file in libiberty also contains getopt()
thus resulting in multiple definitions thereof.
While there, kill extraneous -ldl passed into configure - configure detects -ldl successfully.
=> Fix the build of elf2flt on Cygwin

config/debug/strace.in, configure.ac, scripts/functions
Some software starts to adopt xz-only distribution (strace,
gcc-linaro, ...). Better that than deal with cryptic errors like
"cannot find strace-.tar.bz2".
=> Require xz to be present

patches/glibc/2.12.1/300-macos-cross-rpcgen.patch, patches/glibc/2.12.2/300-macos-cross-rpcgen.patch, patches/glibc/2.13/300-macos-cross-rpcgen.patch, patches/glibc/2.14.1/300-macos-cross-rpcgen.patch, patches/glibc/2.14/300-macos-cross-rpcgen.patch, patches/glibc/2.15/300-macos-cross-rpcgen.patch, patches/glibc/2.16.0/300-macos-cross-rpcgen.patch, patches/glibc/2.17/300-macos-cross-rpcgen.patch, patches/glibc/2.18/300-macos-cross-rpcgen.patch
=> Backport the fix from 2.19 for cross-rpcgen on macos

scripts/crosstool-NG.sh.in
Having .. in it breaks GCC's relocatability.
=> Sanitize CT_PREFIX_DIR, too

patches/linux/2.6.32.27/100-unifdef-strclpy.patch
... which fails to compile due to incompatible prototype for strlcpy()
which isn't even used.
2.6.33 dropped the prototype, so the patch is n/a for newer kernels.
=> Fix unifdef in Linux 2.6.32 on macos

scripts/build/companion_tools/050-make.sh
make's configure uses pkg-config to detect if Guile should be enabled;
on ArchLinux, this picks up Guile from build machine's pkg-config and then
it fails to compile.
A better solution might be to create a ${CT_HOST}-pkg-config in
buildtools/bin that would report "unsupported" for all packages.
However a quick grep only showed pkg-config being used by GCJ
(not sure if it will build in canadian cross - we don't have any
samples with GCJ) and Blackfin simulator in GDB (Blackfin is not
currently supported by crosstool-ng). Hence, leave such pkg-config
implementation and testing for another day.
=> Disable Guile in make if building for host in canadian

config/libc.in, scripts/build/internals.sh
... enabled by default for multilib and disabled otherwise. Buildroot
has been complaining about /etc/ld.so.conf presence for almost a year
now and I missed that.
After the release, xldd will be modified to query the compiler for
the list of multilibs to search. This would be too invasive change
before 1.23, though.
Note that it may lead to configurations where xldd currently does not
find the libraries (if both DEMULTILIB and CREATE_LDSO_CONF are turned
off). This is not the default setting in Kconfig, though.
=> Make creation of ld.so.conf optional

config/target.in
It is only used if this libc flavor uses a multilib iterator (and not
determines the multilibs itself). This class currently includes glibc,
uClibc, musl - but they explicitly select CC_CORE_PASSES_NEEDED anyway.
=> Remove explicit core passes selection for multilib

config/cc/gcc.in.2, config/debug/gdb.in.cross, config/toolchain.in, scripts/crosstool-NG.sh.in
... when determining if it can be linked statically, and if Python
scripting should default to y.
Prompted by a failure of i686-w64-mingw32,nios2-spico-elf sample
on a system where configure didn't report static linking support.
A similar issue was then found in gcc configuration, fixed as well.
=> cross-gdb: account for canadian/crossnative toolchains

scripts/build/binutils/binutils.sh, scripts/functions
On cygwin, creating both "foo.exe" and "foo" results in 'ln -sf'
returning an error ("File exists"). However, ln silently removes
the "foo.exe" in this case, so an attempt to re-run the same command
manually then succeeds.
Hence, make binutils.sh also create symlinks with .exe prefix,
using the new & shiny routine.
=> Fix symlinking to multiarch tools on Cygwin

config/libc/mingw.in, scripts/build/libc/mingw.sh
Without this flag, MinGW does not expose secure variants of functions
such as strcpy_s.
See https://sourceforge.net/p/mingw-w64/mingw-w64/ci/master/tree/mingw-w64-headers/crt/sec_api/string_s.h#l11.
=> MinGW: add --enable-secure-api config option

scripts/functions
=> Avoid creating symlinks with empty prefix

patches/gcc/4.8.5/874-gcc-xtensa-fix-fprintf-format-specifiers.patch, patches/gcc/4.9.4/875-gcc-xtensa-fix-fprintf-format-specifiers.patch, patches/gcc/5.4.0/879-gcc-xtensa-fix-fprintf-format-specifiers.patch, patches/gcc/6.3.0/873-gcc-xtensa-fix-fprintf-format-specifiers.patch, patches/gcc/7.1.0/870-gcc-xtensa-fix-fprintf-format-specifiers.patch
Hi Alexey,
please pull the following fix for xtensa gcc:
xtensa GCC incorrectly uses %ld/0x%lx format specifiers to output
HOST_WIDE_INT values, which results in incorrect code generation by the
compiler built for armhf host.
The original issue:
https://github.com/qca/open-ath9k-htc-firmware/issues/130
Thanks.
-- Max
=> gcc: xtensa: backport fix for incorrect code generation

config/arch/msp430.in, config/target.in, samples/msp430-unknown-elf/crosstool.config, samples/msp430-unknown-elf/reported.by, scripts/build/arch/msp430.sh
Added support for the MSP430 architecture. 
First patch to crosstool-ng, fully anticipating some feedback. In particular the hack added to set `CT_TARGET_SKIP_CONFIG_SUB="y"` in `CT_DoArchTupleValues ` seems likely to produce pushback, but it annoyed me that I couldn't use msp430-elf as my target (the canonicalizer in config.sub overrides the empty `CT_TARGET_VENDOR`).
Signed-off-by: Andrew Wygle <awygle@gmail.com>
=> Added MSP430 architecture support

debian/changelog, debian/control, debian/copyright, debian/rules, debian/source/format
Support building in tree and from a released tarball by optionally
running ./bootstrap.
Fix some issues reported by lintian.
-E: crosstool-ng changes: bad-distribution-in-changes-file unstable
-E: crosstool-ng source: build-depends-on-essential-package-without-using-version build-depends: gzip
-E: crosstool-ng source: build-depends-on-essential-package-without-using-version build-depends: tar
-W: crosstool-ng source: syntax-error-in-dep5-copyright line 14: Cannot parse line "Unless otherwise stated in individual files, this work is licensed to you under"
-E: crosstool-ng: copyright-should-refer-to-common-license-file-for-lgpl
-E: crosstool-ng: description-starts-with-package-name
-E: crosstool-ng: section-is-dh_make-template
-E: crosstool-ng: depends-on-obsolete-package depends: texi2html …
=> debian: update packaging

config/debug/gdb.in.gdbserver, config/debug/gdb.in.native
GDB8 (or rather gnulib that is a part of it) provides a fallback mbstate_t
definition - but GCC's C++ headers (which are used via stdint.h since GDB8
uses C++) provide another mbstate_t if libc does not have wide char support.
These two definitions conflict with each other.
=> Force wide char support in uClibc if GDB8 is enabled

config/arch/msp430.in, samples/msp430-unknown-elf/crosstool.config, samples/msp430-unknown-elf/reported.by
... as GCC5 and later ICEs over inocuous code.
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=79242
=> Declare msp430 experimental

config/arch/arm.in.2, config/target.in
=> Make ARM32 option appear only if 32-bit is selected

scripts/crosstool-NG.sh.in
Fixes #731
CT_BUILD_DIR is used in CT_DoExecLog. We need to ensure that it is
set before the first call to CT_DoExecLog.
=> Set CT_BUILD_DIR prior to using it

.travis.sh, .travis.yml
Running more jobs in parallel lets us squeak in under the 50 min limit.
Switch to trusty and ensure we have g++ available
=> Travis updates

config/debug/gdb.in.gdbserver, scripts/build/debug/300-gdb.sh
Workaround for issue #753
Before:
```
libdl.so.2 => /lib/libdl.so.2 (0x400dc000)
libstdc++.so.6 => /lib/libstdc++.so.6 (0x400ef000)
libm.so.6 => /lib/libm.so.6 (0x4027c000)
libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x4007b000)
libc.so.6 => /lib/libc.so.6 (0x40341000)
/lib/ld-linux.so.3 (0x4004a000)
```
After:
```
libdl.so.2 => /lib/libdl.so.2 (0x401e0000)
libm.so.6 => /lib/libm.so.6 (0x400f7000)
libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x401f3000)
libc.so.6 => /lib/libc.so.6 (0x40223000)
/lib/ld-linux.so.3 (0x400c4000)
```
=> Add option to build gdbserver for target that does not require libstdc++.so

config/arch/nios2.in
Gcc for Nios II does not support -mcpu option, and --with-cpu=XXX flag
breaks gcc compilation. Use --with-arch instead.
Signed-off-by: Kirill Smirnov <kirill.k.smirnov@gmail.com>
=> nios2: fix architecture features

config/companion_libs/expat.in
Expat 2.2.0 and earlier were affected by CVE-2017-923. Expat 2.2.1
provides the corresponding security fixes.
=> Bump expat version to 2.2.1 for security fixes

scripts/functions
Tarball extensions list already contains leading dot,
do not add another one.
Signed-off-by: Kirill Smirnov <kirill.k.smirnov@gmail.com>
=> scripts: remove superfluous dot

packages/glibc/2.12.1/998-obstack-common.patch, packages/glibc/2.12.2/998-obstack-common.patch, packages/glibc/2.13/998-obstack-common.patch, packages/glibc/2.14.1/998-obstack-common.patch, packages/glibc/2.14/998-obstack-common.patch, packages/glibc/2.15/998-obstack-common.patch, packages/glibc/2.16.0/998-obstack-common.patch, packages/glibc/2.17/998-obstack-common.patch, packages/glibc/2.23/997-regexp-common.patch, packages/glibc/2.24/997-regexp-common.patch, packages/glibc/2.25/997-regexp-common.patch
Binutils 2.29 are more picky about versioning of common symbols.
Fix two offenders in glibc versions as applicable.
=> Fix regressions after binutils 2.29

TODO, packages/mingw-w64/v2.0.10/200-gendef-explicit-fallthrough.patch, packages/mingw-w64/v3.0.0/200-gendef-explicit-fallthrough.patch, packages/mingw-w64/v3.0.0/300-genpeimg-explicit-fallthrough.patch, packages/mingw-w64/v3.1.0/200-gendef-explicit-fallthrough.patch, packages/mingw-w64/v3.1.0/300-genpeimg-explicit-fallthrough.patch, packages/mingw-w64/v3.2.0/200-gendef-explicit-fallthrough.patch, packages/mingw-w64/v3.2.0/300-genpeimg-explicit-fallthrough.patch, packages/mingw-w64/v3.3.0/200-gendef-explicit-fallthrough.patch, packages/mingw-w64/v3.3.0/300-genpeimg-explicit-fallthrough.patch, packages/mingw-w64/v4.0.6/200-gendef-explicit-fallthrough.patch, packages/mingw-w64/v4.0.6/300-genpeimg-explicit-fallthrough.patch, packages/mingw-w64/v5.0.2/200-gendef-explicit-fallthrough.patch, packages/mingw-w64/v5.0.2/300-genpeimg-explicit-fallthrough.patch
Modified by Alexey Neyman: remove obsoleted v5.0.1, propagate the patches
to older versions.
Signed-off-by: Kirill Smirnov <kirill.k.smirnov@gmail.com>
=> patches/mingw-w64: Fix build with gcc7

packages/gcc/4.8.5/875-xtensa-fix-PR-target-82181.patch, packages/gcc/4.9.4/876-xtensa-fix-PR-target-82181.patch, packages/gcc/5.4.0/880-xtensa-fix-PR-target-82181.patch, packages/gcc/6.4.0/870-xtensa-fix-PR-target-82181.patch, packages/gcc/7.2.0/870-xtensa-fix-PR-target-82181.patch
Hi Alexey,
please pull the following patch that fixes ICE in all versions of xtensa gcc.
Memory references to DI mode objects could incorrectly be created at
offsets that are not supported by instructions l32i/s32i, resulting in
ICE at a stage when access to the object is split into access to its
subwords:
drivers/staging/rtl8188eu/core/rtw_ap.c:445:1:
internal compiler error: in change_address_1, at emit-rtl.c:2126
Fixes: https://lkml.org/lkml/2017/9/10/151
Signed-off-by: Max Filippov <jcmvbkbc@gmail.com>
=> package/gcc: fix ICE on xtensa, PR target/82181

Makefile.in, configure.ac
Allow to override build date
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
This date call is designed to work with both GNU date and BSD date.
Note: is not properly tested yet
=> Allow for reproducible builds

scripts/functions
Instead, use new variable ${pkg_dir} to locate auxiliary files.
Fixes #838.
=> Do not change {pkg}_VERSION

scripts/functions
... as 'tar' does not follow symlink, rather creating a new directory instead.
=> When handling overlay, move rather than symlink

packages/gettext/0.19.8.1/120-Fix-Woe32-link-errors-when-compiling-with-O0.patch
Otherwise, make tries to rebuild it and fails.
Fixes #770.
=> Include Makefile.in in gettext 0.19.8.1 patch

scripts/build/debug/300-gdb.sh
These changes mainly fix static linking errors when building static
native gdb and gdbserver (tested with gcc 7.2.0 + uClibc-ng 1.0.27 +
binutils 2.29.1 for MIPS):
[ALL  ]    .../lib/libstdc++.a(eh_throw.o): In function `__cxa_throw':
[ALL  ]    (.text.__cxa_throw+0x64): undefined reference to `_Unwind_RaiseException'
[ALL  ]    (.text.__cxa_throw+0x6c): undefined reference to `_Unwind_RaiseException'
[ALL  ]    .../lib/libstdc++.a(eh_throw.o): In function `__cxa_rethrow':
[ALL  ]    (.text.__cxa_rethrow+0x78): undefined reference to `_Unwind_Resume_or_Rethrow'
[ALL  ]    (.text.__cxa_rethrow+0x80): undefined reference to `_Unwind_Resume_or_Rethrow'
...
The problem is in mixing of CPP, CC, CXX, and LD with CPPFLAGS, CFLAGS,
CXXFLAGS, and LDFLAGS before passing to configure scripts.
gcc is …
=> Fix variables passing to gdb configure scripts

scripts/build/debug/300-gdb.sh
Build flags are scalar variables.
=> Fix gdb build flags forming

bootstrap
On some systems (e.g. macOS), the bash provided by the system at `/bin/bash` is not new enough for the bootstrap script, while users may install a bash instance elsewhere. In that case, `/usr/bin/env` can get the bash in the current environment.
=> Use /usr/bin/env to locate bash

scripts/build/arch/sh.sh
Otherwise, binutils don't recognize it as a valid target - even though
GCC does.
Fixes #897.
=> Only decorate TARGET_ARCH if using specific CPU

kconfig/kconfig.mk
Otherwise, a file named `defconfig` (which is, ironically, the default name
for the default config expected by this very makefile) prevents the defconfig
target from being run.
=> Make defconfig (and a bunch of other targets) phony

scripts/build/cc/gcc.sh
This fixes gccs LIMITS_H_TEST detection for baremetal targets
so limits.h will be installed correctly.
Signed-off-by: Michael Zimmermann <sigmaepsilon92@gmail.com>
=> cc/gcc: use correct sysroot arg for do_gcc_core_backend

scripts/functions
... see the comment for the reason. Defer aborting until the result of
CT_Mirrors is actually used (if it is used).
=> Avoid calling CT_Abort from CT_Mirrors

Makefile.in
Fixes #934
Add a rule that errors out with a message if configure.ac is newer than
configure. This should catch times where someone is building from the
repo without running bootstrap.
=> Makefile.in: check for configure being up to date

samples/samples.mk
Partially addresses issue #923 
aarch64-rpi3-linux-gnu needs update:
diff: `-0' option is obsolete; use `-U 0'
diff: Try `diff --help' for more information.
=> fix deprecated diff option

kconfig/Makefile.am
... to libtool, to allow CC overrides at make stage.
Fixes #940.
=> Supply explicit --tag CC

m4/ax_with_curses_extra.m4
#942 I did some research and found a modification to ax_with_curses_extra.m4 that should cause it to recognize <panel.h> better. I found something about it in the changelog of this repo and reproduced the change.
https://github.com/Tlf/tlf
I figured I should give credit where it is due
=> modified ax_with_curses_extra.m4 to have better regocnition of <panel.h>

debian/rules
Since fda857aeb851e5329b5dec664cc14903bf4d20a6 and d6f5c308f9b9564df548d7d6a245a56dbf5360bc, there is no longer any need to override dh_auto_install
=> debian: no need to override dh_auto_install

configure.ac
As we support CentOS, for example, we have a problem there
automake: warnings are treated as errors
kconfig/Makefile.am:26: warning: compiling 'lxdialog/checklist.c' in subdir requires 'AM_PROG_CC_C_O' in
'configure.ac'
autoreconf: automake failed with exit status: 1
https://www.gnu.org/software/automake/manual/html_node/Public-Macros.html
CentOS 7, automake 1.13
=> Add compatibility with automake < 1.14

debian/control
If these are not present during build, we will end up with a ct-ng that can't download anything.
=> debian: include curl and wget in Build-Depends

packages/gcc/8.1.0/0018-ARC-Reimplement-return-padding-operation-for-ARC700.patch
Without this fix we're getting the following error on attempt to build
Linux kernel:
--------------------------------->8---------------------------------
xfrm4_mode_tunnel.s: Assembler messages:
xfrm4_mode_tunnel.s:188: Error: operand out of range (128 is not between -
128 and 127)
--------------------------------->8---------------------------------
The fix is taken from
https://github.com/foss-for-synopsys-dwc-arc-processors/gcc/commit/d8d716f49c0057e239f2b64e7d902046b92d244f
and it is supposed to be merged in upstream GCC sources soonish.
Signed-off-by: Alexey Brodkin <abrodkin@synopsys.com>
=> ARC: Fix Linux kernel compilation for ARC700

packages/mpfr/4.0.1/0001-Fix-obsolete-ARC-asm-constraints.patch
Adding this patch fixes errors while building mpfr for native ARC
toolcahin. Error messages are:
-----------------------------------------------------8<------------------
...
[ERROR]   .build/HOST-arc-snps-linux-uclibc/arc-snps-linux-uclibc/src/
mpfr/src/mpfr-longlong.h:423:3: error: impossible constraint in 'asm'
...
[ERROR]  >>  Build failed in step 'Installing MPFR for host'
-----------------------------------------------------8<------------------
Signed-off-by: Evgeniy Didin <didin@synopsys.com>
=> patches: mpfr: Fix obsolete ARC asm constraints

scripts/build/libc/newlib.sh
=> Fix a wrong name for the newlib's multilib option

packages/gcc/5.5.0/0034-xtensa-fix-PR-target-65416.patch, packages/gcc/6.4.0/0034-xtensa-fix-PR-target-65416.patch, packages/gcc/7.3.0/0022-xtensa-fix-PR-target-65416.patch, packages/gcc/8.1.0/0021-xtensa-fix-PR-target-65416.patch
Hi Alexey,
please merge the following patch that adds fix for xtensa gcc PR target/65416 to ct-ng gcc versions 5...8.
Thanks.
-- Max
=> package/gcc: fix xtensa PR target/65416

kconfig/symbol.c
Commit 1c199f2878f6 ("kbuild: document recursive dependency limitation
/ resolution") probably intended to show a hint along with "recursive
dependency detected!" error, but it missed to add {...} guard, and the
hint is displayed in every loop of the dep_stack traverse, annoyingly.
This error was detected by GCC's -Wmisleading-indentation when switching
to build-time generation of lexer/parser.
scripts/kconfig/symbol.c: In function ‘sym_check_print_recursive’:
scripts/kconfig/symbol.c:1150:3: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
if (stack->sym == last_sym)
^~
scripts/kconfig/symbol.c:1153:4: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
fprintf(stderr, "For a resolution refer to …
=> kconfig: display recursive dependency resolution hint just once

scripts/build/libc/bionic.sh
Modify CT_TARGET_CFLAGS (which are passed to GCC's FOR_TARGET flags) rather
than CT_ALL_TARGET_CFLAGS.
Fixes #1006.
=> Restore *-android build

scripts/build/libc/newlib.sh
Some configuration-time flags for newlib are prefixed with "newlib-", i.e. we need to pass --enable-newlib-FEATURE to the configure script. Unfortunately, newlib.sh do not add this prefix when enabling the features atexit-dynamic-alloc, reent-small, multithread, and unbuf-stream-opt. Thus, enabling these options in crosstool-ng's config has no effect on the generated libc.
This patch fixes this bug.
=> Properly handle newlib configuration flags

packages/gcc/8.2.0/0020-ARM-fix-cmse.patch, packages/gcc/8.2.0/0021-arm-Make-arm_cmse.h-C99-compatible.patch
There are some fixes to the cmse code in mainline gcc that we need to
build an embedded toolchain targetting Cortex-M cpus that support the
v8m extensions.
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
=> Pull in fixes for ARM v8m support in gcc 8.2.0

packages/elf2flt/git-6d80ab6c93409e796f85da404bde84b841231531/0000-diagnostics.h.patch
... where <bfd/bfd.h> also needs <bfd/diagnostics.h>.
=> Fix compilation against binutils-2.31.1

packages/android-ndk/r18/DO_NOT_IMPORT, packages/android-ndk/r18/chksum
It no longer supports GCC.
Fixes #1047.
=> Remove android-ndk-r18

scripts/build/libc/glibc.sh
... so that it works in both "bundled" and "bundled,local" cases.
Fixes #1060.
=> Create glibc-ports symlink inside CT_SRC_DIR

scripts/build/cc/gcc.sh
... as 1.0 and 99.99, respectively, to gcc configure.
Fixes #1031.
=> Supply "very old" and "very new" glibc versions

scripts/functions
The function is called from a conditional and therefore, the CT_OnError
handler is not invoked on failures. Need to return an error and check
for the error return in the caller.
Also, while here, fix the issue that was causing the failure -
move can fail if it crosses a filesystem, so fall back to 'cp+rm' in
that case.
=> Detect errors in CT_SaveLocal

config/arch/arc.in, packages/linux/package.desc
Inspired by a similar fix for AArch64 in 481cbaac9b23.
The point is in Linux v4.8 we introduced new ABIv4 which is now used in
both Linux kernel and up-to-date GNU tools for ARC (based on GCC 6.x+).
See [1] for more details.
[1] https://github.com/foss-for-synopsys-dwc-arc-processors/linux/wiki/ARC-Linux-Syscall-ABI-Compatibility
Signed-off-by: Alexey Brodkin <abrodkin@synopsys.com>
=> Disallow linux versions before 4.8 for ARC

scripts/build/binutils/binutils.sh, scripts/functions
... and use that ability to permanently set CTNG_LD_IS in case gold is default linker
and we're building glibc.
Fixes #988. This was a long-standing breakage in crosstool-NG (at least since it began
to run each step in a sub-shell).
=> Add an ability to modify an exported variable

scripts/build/cc/gcc.sh
I had a problem when compiled ct-ng for a custom bare-metal arch. It didn't find "pthread.h" header and others
=> Use the platform headers in the pass-2 and canadian gcc stages

configure.ac
Sometimes ago I noticed 'file' and 'which' missed dependencies. The first one you've added recently
=> Add a "which" dependency into the configure script

scripts/functions
Just a useful thing, it adds an ability to use a regular directory for overlaying.
If the directory  doesn't exist, the tarball is still used.
=> Regular directory for overlaying

ct-ng.in
After d4aa8d9, make distclean removes scripts in ct-ng configured
with --enable-local.
=> Fix distclean

Makefile.am, bootstrap, ct-ng.in, scripts/functions, scripts/scripts.mk
... for ct-ng configured without --enable-local. Also, install
licenses in subdirectories of the components.
Also, ct-ng configured with --enable-local removed the scripts directory
upon `ct-ng distclean`.
Also, misspelled CT_WGET/CT_CURL variables prevented use of
`ct-ng updatetools`.
Fixes #1091.
=> Fix installation of the license file

scripts/build/binutils/binutils.sh, scripts/build/cc/gcc.sh, scripts/build/internals.sh
... so that ar can find the plugin even when invoked directly, not
via the gcc-ar plugin.
Fixes #1113.
=> Add a symlink to LTO for binutils

scripts/build/libc/uClibc.sh, scripts/crosstool-NG.sh, scripts/functions
This way, a uClibc-based toolchain is reproducible. `.config` has the `ct-ng` version and the `ct-ng` configuration,  but the external uClibc configuration (if supplied) is not part of the build output.
=> Store the uClibc .config alongside the ct-ng .config

kconfig/Makefile.am
I got this error when compiling crosstool-ng with CYGWIN:
```
/usr/bin/libtool  --tag CC  --mode=link gcc  -g -O2   -o conf.exe conf.o zconf.o
libtool: link: gcc -g -O2 -o .libs/conf.exe conf.o zconf.o
mv -f .deps/nconf-zconf.Tpo .deps/nconf-zconf.Po
depbase=`echo lxdialog/checklist.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I. -I../../crosstool-ng/kconfig -I..  -include config.h -DCONFIG_=\"CT_\"   -g -O2 -MT lxdialog/checklist.o -MD -MP -MF $depbase.Tpo -c -o lxdialog/checklist.o ../../crosstool-ng/kconfig/lxdialog/checklist.c &&\
mv -f $depbase.Tpo $depbase.Po
conf.o: In function `conf_askvalue':
/home/carlo/c2/kconfig/../../crosstool-ng/kconfig/conf.c:90: undefined reference to `libintl_gettext'
/home/carlo/c2/kconfig/../../crosstool-ng/kconfig/conf.c:90:(.text+0x148) …
```
=> Correctly reference to libintl when linking.

config/kernel.in
... unless experimental. This unbreaks m68k-uclinux-uclibc sample which
after the recent change in uClibc.sh attempted to build a shared flat
library and failed. We were not building shared flat libraries before.
=> Don't enable "shared flat"

scripts/build/companion_libs/210-expat.sh
This fixes following build error on Debian 9:
configure: error: Your local docbook2man was found to work with SGML rather
than XML. Please install docbook2X and use variable DOCBOOK_TO_MAN to point
configure to command docbook2x-man of docbook2X.
Or use DOCBOOK_TO_MAN="xmlto man --skip-validation" if you have xmlto around.
You can also configure using --without-docbook if you can do without a man
page for xmlwf.
Signed-off-by: Bernhard Walle <bernhard@bwalle.de>
=> expat: Build without docbook

testing/docker/archlinux/Dockerfile
... awhile ago; I had it cached on one machine.
=> Seems like ArchLinux renamed its base on dockerhub

config/libc/uClibc.in
Currently if we select uclibc debug level "all" then uclibc will be compiled without debug at all.
This bug was added in commit 2aee11cc when new level of uclibc debugging ("normal") was introduced.
=> uClibc: fix selection of debug level

samples/arm-cortexa5-linux-uclibcgnueabihf/reported.by, samples/arm-unknown-linux-uclibcgnueabi/reported.by
G+ is now defunct, update the reporter_url to bootlin as both Thomas and I
are working there.
Signed-off-by: Alexandre Belloni <alexandre.belloni@bootlin.com>
=> samples: G+ is gone, update reporter_url

scripts/build/kernel/linux.sh, scripts/build/libc/uClibc.sh
Hello,
please pull the following two small fixes: one adds support for building noMMU xtensa toolchains and the other fixes building uClibc when dynamic target libraries are not available.
Thanks.
-- Max
=> noMMU xtensa fixes

config/arch/riscv.in, testing/docker/ubuntu16.04/Dockerfile, testing/docker/ubuntu18.04/Dockerfile, testing/docker/ubuntu18.10/Dockerfile
Retesting Ubuntu18.10 for build-all, and - if no other regressions - releasing.
=> Last fixes for 1.24

packages/glibc/2.29/0001-Add-ARC-architecture.patch
Fixes: #1227
Adjust the ARC patch so that it only sets with_fp_cond when the machine
is arc.
https://github.com/foss-for-synopsys-dwc-arc-processors/glibc/issues/7
=> glibc: arc: Don't interfere with other architectures

scripts/build/internals.sh
Fixes: #887
On some systems the file command identifies a pie executable as a shared
object. Update do_finish() to handle this case so that they are stripped
as well.
=> build/internals.sh: Handle pie executables

config/libc/glibc.in
Fixes: #1210
Per the release notes for the GNU C library 2.28[1] make 4.0 or newer is
required. Previously the logic was applied to glibc 2.29 or newer.
[1] - https://www.sourceware.org/ml/libc-alpha/2018-08/msg00003.html
=> libc: glibc 2.28 needs make 4.0

packages/zlib/package.desc
Currently, SourceForge is down and downloads give a 500 error. That's
not overly uncommon (even less often the case these days). Fortunately,
zlib provides another mirror on their homepage, add that as option to
the package description. (https://www.zlib.net/)
=> zlib: Provide other mirror

config/libc/newlib.in, scripts/build/libc/newlib.sh
This commit adds support for the newlib configuration option
'--enable-newlib-retargetable-locking'.
Signed-off-by: Stephanos Ioannidis <root@stephanos.io>
=> Add newlib retargetable locking configuration

scripts/build/libc/musl.sh
I was trying to build static binaries for a range of Broadcom soft-float ARMv7
SoCs and kept getting SIGILL, although I was targeting Cortex A7 (and A5,
later), even on A9 and A15.
I found out that once I add -msoft-float, +mp+sec is to blame:
```
Attribute Section: aeabi
File Attributes
-  Tag_CPU_name: "7VE"
+  Tag_CPU_name: "7"
Tag_CPU_arch: v7
-  Tag_CPU_arch_profile: Application
-  Tag_ARM_ISA_use: Yes
Tag_THUMB_ISA_use: Thumb-2
Tag_ABI_PCS_wchar_t: 4
Tag_ABI_FP_rounding: Needed
@@ -12,8 +10,5 @@ File Attributes
Tag_ABI_FP_number_model: IEEE 754
Tag_ABI_align_needed: 8-byte
Tag_ABI_enum_size: int
Tag_ABI_optimization_goals: Aggressive Size
Tag_CPU_unaligned_access: v6
-  Tag_MPextension_use: Allowed
-  Tag_DIV_use: Allowed in v7-A with integer division extension
- …
```
=> Resepct CT_TARGET_{C,LD}FLAGS when building musl

config/binutils/binutils.in, scripts/build/binutils/binutils.sh
This adds an option to configure bintuils with `--enable-deterministic-archives`.
The default is set to enabled as there schould be hardly anyone depending on the noise in static libraries, most people either 
- do not know that ar archives contain stuff like timestamps, uids
- do know because it messes up their [Reproducible builds](https://reproducible-builds.org/)
- do know and could not care less
=> enable option for binutils deterministic-archives

config/global/paths.in, scripts/crosstool-NG.sh
this allows users to reference this variable,
for ex. in TARGET_CFLAGS to remap paths.
Idea is to remap all debug-info to ${CT_PREFIX}/src/gcc-${CT_GCC_VERSION} and so on, so you can easily debug.
multilib makes this kinda hard (especially for arm). Might try to add this as feature directly to ct-ng later.
=> move BUILD_DIR variable into Kconfig

scripts/build/libc/glibc.sh
The glibc will append the content of the CFLAGS variable,
overriding previous flags.
If unset, the CFLAGS variable is not empty, so explicitly set it.
Instead prepend the default CFLAGS flags.
=> prevent the glibc build from overwriting flags

testing/docker/alpine3.8/Dockerfile, testing/docker/archlinux/Dockerfile, testing/docker/centos6/Dockerfile, testing/docker/centos7/Dockerfile, testing/docker/fedora29/Dockerfile, testing/docker/gentoo-amd64/Dockerfile, testing/docker/mint19-amd64/Dockerfile, testing/docker/ubuntu16.04/Dockerfile, testing/docker/ubuntu18.04/Dockerfile, testing/docker/ubuntu19.10/Dockerfile
Make the creation of docker images easier so that CTNG_UID/CTNG_GID have
a default value if it's not explicitly specified when building. This
will allow publishing of images on various package repositories (e.g.
docker hub, gitlab containers). dmgr.sh can still be used to set the
UID/GID to that of the current user when building a custom container.
=> testing/docker: set default value for CTNG_UID/CTNG_GID

Makefile.am
... because if it is invoked via create-release.sh, it it not possible
to pass the variables to make otherwise.
=> Allow environment override of USE_GPG/DIGESTS

packages/glibc/package.desc
... but no definition after af2f3ac9c.
=> GLIBC 2.28 milestone has a dependency

.github/workflows/continuous-integration-workflow.yml
This series creates a continuous integration configuration using github actions. I've arbitrarily chosen some samples to build. I'd like to expand this to at least one of each supported architecture and hopefully we can cover off each libc variant within that.
An example of this in action can be seen here https://github.com/cpackham/crosstool-ng/actions
=> CI: Use github actions for continous integration

scripts/build/debug/300-gdb.sh
This series fixes the incorrect reference to the `CT_GDB_NATIVE_STATIC_LIBSTDCXX` configuration and semantically aligns it with the equivalent GCC symbol (`CT_CC_GCC_STATIC_LIBSTDCXX`).
CI run here (ignore the "cancelled" failures):
https://github.com/stephanosio/zephyr-crosstool-ng/actions/runs/115500663
=> Fix CT_GDB_NATIVE_STATIC_LIBSTDCXX

packages/zlib/1.2.11/0003-crossbuild-macos-libtool.patch, scripts/crosstool-NG.sh
A fix for cross-build for macos
```
...
[INFO ]  Installing zlib for host
[DEBUG]    Entering '/builds/idf/crosstool-NG/.build/HOST-x86_64-apple-darwin12/xtensa-esp32-elf/build/build-zlib-host-x86_64-host_apple-darwin12'
[EXTRA]    Configuring zlib
[DEBUG]    ==> Executing:  CFLAGS='-O2 -g -pipe -I/builds/idf/crosstool-NG/.build/HOST-x86_64-apple-darwin12/xtensa-esp32-elf/buildtools/complibs-host/include  -fno-common' LDFLAGS='-L/builds/idf/crosstool-NG/.build/HOST-x86_64-apple-darwin12/xtensa-esp32-elf/buildtools/complibs-host/lib  -framework CoreFoundation' CHOST='x86_64-host_apple-darwin12' '/bin/bash' '/builds/idf/crosstool-NG/.build/HOST-x86_64-apple-darwin12/xtensa-esp32-elf/src/zlib/configure' '--prefix=/builds/idf/crosstool-NG/.build/HOST-x86_64-apple-darwin12/xtensa-esp32-elf/buil …
```
=> zlib-1.2.11: Add a patch to cross-compile for macos

config/libc/glibc.in, packages/glibc/package.desc
When building powerpc64+glibc-2.32 we see the following error:
[ALL  ]      In file included from ../sysdeps/powerpc/powerpc32/power4/multiarch/wordcopy-ppc32.c:26,
[ALL  ]                       from ../sysdeps/powerpc/powerpc64/multiarch/wordcopy-ppc64.c:18:
[ALL  ]      ../string/wordcopy.c: In function '_wordcopy_fwd_aligned':
[ERROR]      ../string/wordcopy.c:98:26: error: 'a1' may be used uninitialized in this function [-Werror=maybe-uninitialized]
[ALL  ]         98 |       ((op_t *) dstp)[0] = a1;
[ALL  ]            |       ~~~~~~~~~~~~~~~~~~~^~~~
[ALL  ]      In file included from ../sysdeps/powerpc/powerpc64/power4/../../powerpc32/power4/memcopy.h:38,
[ALL  ]                       from ../sysdeps/powerpc/powerpc64/power4/memcopy.h:1,
[ALL  ]                       from …
=> glibc: Don't build with -Werror for powerpc64+glibc-2.32

bootstrap
cmp, u1, u2 seem not to be used at all.
=> Remove unused variables in bootstrap

config/libc/glibc.in
Make --enable-obsolete-rpc conditional on !CT_GLIBC_2_32_or_later as
it's been removed from that version on.
=> glibc: --enable-obsolete-rpc has been removed as of 2.32

scripts/build/arch/powerpc.sh, scripts/build/libc/picolibc.sh, scripts/functions
I missed a couple of changes required to build crosstool-ng for targets other than 32-bit ARM. 
1. Make non-arm architectures use the same CT_TARGET_SYS value as is used for newlib (generally 'elf').
2. Use selected architecture values when configuring the meson cross-compile environment for picolibc.
=> Picolibc for more than just arm

scripts/functions
Before patches for specific package were searched in packages/${pkg_name}/${version}. This means that with usage of custom
version, patches wont be applied. This commit makes ct-ng search bundled patches also in packages/${pkg_name} directory. That means that we can put some patches in this directory, that will be applied to any version of this component.
This change is useful for development purposes when you build toolchain from custom sources and you need some patches to be applied, so you can put required patches in the top package directory.
=> Patches: search package patches in the top package directory

packages/glibc/2.32/0001-Set-version.h-RELEASE-to-stable-Bug-26700.patch, scripts/build/libc/glibc.sh
Backport change from glibc upstream that defines RELEASE as stable
instead of release. This will at least cause the default_cflags to be
set to expected default values again.
Ref issue #1396, although the bigger issue of respecting crosstool-ng
CT_GLIBC_EXTRA_CFLAGS is most likely still not fixed.
=> glibc: fix version 2.32 not setting correct version string

scripts/build/companion_tools/100-m4.sh
While building a canadian toolchain for windows host (any target),
the build failed for m4 host companion_tool with a recent mingw-w64
(at least 7.0.0).
m4 needs stack smashing protection which is not part of mingw-w64 c
library and an explicit trigger to link w/ libssp is needed.
Signed-off-by: Florent Valette <florent.valette@gmail.com>
=> m4: fix build for mingw32 host

config/global/extract.in
Currently the help for LOCAL_PATCH_DIR did not specify the tree layout
of custom patches directory. This commit adds such explanation.
For example, the bundled patches for GCC are placed under
packages/gcc/<gcc-version>, thus custom (local) GCC patches should be
placed under $LOCAL_PATCH_DIR/gcc/<gcc-version>.
Signed-off-by: Bagas Sanjaya <bagasdotme@gmail.com>
=> Clarify tree layout of local patches directory

scripts/build/binutils/binutils.sh
Since glibc 2.27 glob interface was changed [1]  and so "glob" & "glob64" symbols require glibc 2.27+.
For us that means if we build Binutils on a machine with glibc 2.27+ produced binaries won't be any longer usable on machines with older glibc.
As an example [2]: build on Ubuntu 18.04 (with glibc 2.27) and try to run on CentOS 7.x (with glibc 2.17), you'll see this:
```
$ ldd ld
ld: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by ld)
```
Now given glob is not really used by Binutils itself (only needed by GDB) and we build Binutils & GDB separately let's make at least Binutils more portable.
In theory we may even try to do the same hack for GDB forcing it to use imported glob implementation. But since GDB is now built strictly by C++ compiler we'll get waaay to many …
=> binutils: Disable glob for better portability

scripts/build/libc/uClibc.sh
Using a custom config for uClibc-ng I wanted to enable XLOCALE but found out it is being unconditionally disabled regardless.
Signed-off-by: Lance Fredrickson <lancethepants@gmail.com>
=> Don't unconditionally disable XLOCALE support.

scripts/build/arch/arm.sh
Similar to commit 57679b5e ("Disable context functions for Thumb") when
building for thumb we need to unset UCLIBC_HAS_CONTEXT_FUNCS.
Fixes #1397
=> arm: Disable context functions for Thumb

.github/workflows/continuous-integration-workflow.yml
The add-path and set-env commands are being deprecated[1]. Replace the
one instance of add-path in the CI workflow with the recommended
alternative[2].
[1] - https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
[2] - https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
=> CI: Replace add-path command

packages/gcc/10.2.0/0022-aarch64-fix-conflicting-declarations.patch
If we are targetting an aarch64-none-elf toolchain we end up running
into a build issue in gcc/config/aarch64/driver-aarch64.c.  This is
fixed in upstream gcc so just backport the patch to gcc-10.2.0
Signed-off-by: Kumar Gala <kumar.gala@linaro.org>
=> gcc: Additional build fix for building arm64 toolchain on M1 Mac's

packages/ltrace/package.desc
=> packages/ltrace: Remove stray ':' from URL

packages/ncurses/package.desc
ftp://invisible-island.net/ncurses doesn't actually have the numbered
ncurses tarball. We've not noticed because we fall back to using the GNU
mirror which does. It's also ftp which is being deprecated.
Switch to https://invisible-mirror.net/archives/ncurses which has the
actual tarballs and provides a secure connection.
=> packages/ncurses: update ncurses mirror

scripts/build/cc/gcc.sh
Even though GCC as a compiler has nothing to do with a C library being used it still makes sense to know about Newlib's compact implementation of IO functions:
* For targets like MSP430 which require to have such a tuned Newlib if `-mtiny-printf` is passed to the GCC's command-line (see https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=02afb6a9321fbfb435452636cedc2cd43f0c4fd2).
* For correct compilation of the following GCC's own DejaGnu tests (see https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=571bbd0d48d5872eacbd0b681fce6e1ae754520b):
- gcc/testsuite/gcc.c-torture/execute/920501-8.c
- gcc/testsuite/gcc.c-torture/execute/930513-1.c
- gcc/testsuite/gcc.dg/torture/builtin-sprintf.c
- gcc/testsuite/gcc.c-torture/execute/ieee/920810-1.x
So we add that missing cross-dependency now.
=> gcc: Make it aware of Newlib nano IO feature

scripts/build/companion_libs/100-gmp.sh
Currently when building cross-canadian toolchain for macOS the folowing error happens when GCC is configured:
```
ld: illegal text-relocation to '___gmp_binvert_limb_table' in
... /.build/... /buildtools/complibs-host/lib/libgmp.a(mp_minv_tab.o) from '___gmpn_divexact_1' in
... /.build/... /buildtools/complibs-host/lib/libgmp.a(dive_1.o)
collect2: error: ld returned 1 exit status
```
Apparently this might be solved with GMP configured with `--with-pic`, even though we're talking about static library here.
That solution was found here: https://github.com/Homebrew/homebrew-core/pull/25470
=> libgmp: Fix cross-canadian build for macOS

packages/glibc/2.32/0002-Add-ARC700-support.patch, packages/glibc/2.33/0002-Add-ARC700-support.patch
That fixes build of `arc-multilib-linux-gnu` sample for ARC700. We didn't see that problem previously since we used off-the-tree patch for all ARC processors with glibc pre-2.32 (where ARCv2 port was accepted), since proposed here fix was a part of that patch. Now fix this with ARC700-related diff as compared to vanilla sources.
As of today ARCompact (AKA "ARCv1 ISA") processors (mostly those are ARC770) are not officially supported by upstream glibc as it adds quite some burden on release ans support of yet another "architecture" port.
But given on ABI and ISA front ARCompact is very close to ARCv2 we may easily retrofit its support off-the-tree, which we do here. Thanks to @naheb for taking care of that here: https://github.com/openwrt/openwrt/commit/33646a51abcf15ff5c5363848287e1ed778b7 …
=> glibc: Add ARC700 support to v2.32 & 2.33

.github/workflows/continuous-integration-workflow.yml
As of today baremetal (AKA "Elf32") & Linux glibc toolchains are even more important than Linux uClibc one for ARC, so adding them.
@cpackham if +2 more full multilib toolchains for just one architecture is way too much given amount of resources we have for per-PR testing here, I may drop existing uClibc config.
=> CI: Add miltilibbed Elf32 & glibc configs for ARC

scripts/build/companion_libs/350-newlib_nano.sh
If existing board's .specs are used for linking of a user's application, then instead of normally used libs like `libc.a` & `libstdc++.a` might be requested their "nano"-suffixed siblings: `libc_nano.a`, `libstdc++_nano.a` etc.
That way:
```
%rename link_gcc_c_sequence	myboard_link_gcc_c_sequence
*myboard_libc:
%{!specs=nano.specs:-lc} %{specs=nano.specs:-lc_nano}
*link_gcc_c_sequence:
%(myboard_link_gcc_c_sequence) --start-group %G %(myboard_libc) --end-group
```
Our companion newlib-nano libs are all built optimized for size, so we'd like to use them for linking. But given linker will see `-lc_nano -lstdc++_nano` on its command line non-suffixed libs will be ignored.
To solve it we create those `_nano`-suffixed libraries as simple symlinks to existing libs..
Fixes …
=> newlib-nano: Create symlinks for nano-suffixed libs

.github/workflows/continuous-integration-workflow.yml
Add a configuration that includes musl libc.
=> CI: add arm-unknown-linux-musleabi configuration

ct-ng.in
When I do `./ct-ng oldconfig` (mater branch) I'm getting 
```
CONF  oldconfig
crosstool-NG/kconfig/conf: unrecognized option '--silentoldconfig'
See README for usage info
make: *** [oldconfig] Error 1
ct-ng:130: recipe for target 'oldconfig' failed
```
I found that the cause is https://github.com/crosstool-ng/crosstool-ng/commit/689dc60f212db105243b60290480f29475578e0d
I propose this fix.
=> Make `ct-ng oldconfig` work again after kconfig updating

packages/gcc/10.2.0/0024-libstdc-Fix-bootstrap-with-fno-rtti-PR-99077.patch
Adds a fix for anyone who wants to bootstrap GCC 10 with '-fno-rtti'
=> GCC 10: Fix bootstrap with -fno-rtti

.github/workflows/continuous-integration-workflow.yml
sh-multilib-linux-gnu ends up building 8 different libcs. This seems to
be problematic for the github hosted runners as it appears to run them
out of disk space (anecdotally this seems to have gotten worse with the
switch from ubuntu-18.04 to ubuntu-20.04).
Build sh-unknown-elf instead to make sure we cover of the sh
architecture to some degree.
=> CI: build sh-unknown-elf instead of sh-multilib-linux-gnu

packages/gcc/10.2.0/0025-preprocessor-Make-quoting-PR-95253.patch
Backport gcc commit: https://github.com/gcc-mirror/gcc/commit/1ba71fabb78b18884e9f479f45a257bab50e8959#diff-01d4a2754612370f4a498e10fb94692e0c7e4e9ea1e04fcf7d29c8037d81bb5b 
Here is how it fails without this commit: https://stackoverflow.com/questions/61729611/cmake-mingw-w64-strange-error-when-trying-to-build
The issue is because gcc echoed ':' sign in Windows file paths.
=> Fix depends generation with absolute paths

scripts/build/debug/300-gdb.sh
Note, this is more of precautious "fix", though I'd say pretty meaningful: why touching something we're not going to really use.
Now, w/o that fix it's not possible to build even host/target GDB out of GDB v10.x sources. To get gdbserver built in v10.x we'll
need to do much more (see https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=919adfe8409211c726c1d05b47ca59890ee648f1) as source structure was changed (gdbserver was "promoted" to the top-level, see https://github.com/abrodkin/crosstool-ng/commit/2f9b431228c58fe98704a72390672942935ac8e3).
Yet host or target GDB could be nicely built of v10.x sources just with that one-liner fix.
=> gdb: Don't mess with gdbserver config permissions

packages/ltrace/0.7.3/0008-mips-printf-format.patch
Newer versions of GCC complain:
plt.c: In function 'arch_elf_add_plt_entry':
plt.c:359:3: error: '%s' directive argument is null [-Werror=format-overflow=]
359 |   fprintf(stderr, "%s: failed %s(%#llx): %sn", __func__,
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
360 |    name, addr, strerror(errno));
|    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
add a patch to avoid this error.
=> ltrace: Add patch to fix compile error for mips

scripts/build/companion_libs/350-newlib_nano.sh
In currently generated top-level `nano.specs` we resolve paths during toolchain building and then use those pre-defined
full paths once the toolchain got built.
That's OK until the toolchain is used right where it was built, otherwise paths used in the top-level `nano.specs` become irrelevant and linker fails to find "nano" libs reverting to non-"nano" libs in the default location.
See https://github.com/crosstool-ng/crosstool-ng/issues/1491.
=> newlib-nano: Use run-time calculated paths in top-level nano.specs

scripts/functions
Annotated git tags are git objects with their own ID.
They contain the commit ID where they point to.
When downloading from annotated tags, we currently get the following warning:
"Revision being fetched changed to ${new_unique_id};"
The old unique_id is the ID of the annotated tag and the new unique_id
is the commit it points to.
Let's resolve this by first assuming to have an annotated tag and let
git ls-remote dereference it. If that fails (e.g. if it can't be
dereferenced because it is not an annotated tag), then let's proceed as
before and don't do any dereferencing.
Signed-off-by: Christoph Muellner <cmuellner@linux.com>
=> scripts/functions: Add better support for annotanted git tags

packages/glibc/2.24/0013-fix-cmpli-usage-in-power6-memset.patch
https://sourceware.org/bugzilla/show_bug.cgi?id=20785 
The patch comes from https://github.com/bminor/glibc/commit/78b7adbaea643f2f213bb113e3ec933416a769a8 with minor edit (removed conflicted changelog hunk).
=> Add glibc 2.24 fix cmpli usage in power6 memset patch

config/comp_libs/newlib-nano.in, scripts/build/cc/gcc.sh, scripts/build/companion_libs/350-newlib_nano.sh
This series consists of two important fixes for the libstdc++ build:
1. Fix incorrect optimisation flag when `CT_CC_GCC_ENABLE_TARGET_OPTSPACE=n`.
2. Allow specifying CXXFLAGS for libstdc++ nano build (and use `-fno-exceptions` as default).
=> Fix libstdc++ build options

testing/docker/archlinux/Dockerfile
The name of the docker images have changed on docker hub. Update the
name used to point to the official archlinux image.
Fixes #1522
=> testing: docker: Use archlinux:latest instead of archlinux/base:latest

maintainer/kconfig-versions.template
Prior to commit 30bffa96 SRC_CUSTOM was inside the choice with
SRC_RELEASE and SRC_DEVEL making the 3 options mutually exclusive.
Restore this behaviour keeping the "fix" to keep kconfig happy.
Fixes #1151
Fixes: 30bffa96 ("don't nest choices")
=> Move SRC_CUSTOM inside choice

config/cc/gcc.in, scripts/build/cc/gcc.sh
Explicitly passing --disable-tm-clone-registry causes gcc to create a
crtbegin.o with a zero-sized .init_array/.fini_array. This in turn
causes ld to complain.
Make CC_GCC_TM_CLONE_REGISTRY a tristate so if it's not explicitly
enabled we can let ./configure decide.
Fixes #1531
Fixes: 1e21a302 ("gcc: Add CT_CC_GCC_TM_CLONE_REGISTRY config")
=> gcc: Make CC_GCC_TM_CLONE_REGISTRY tristate

.github/workflows/continuous-integration-workflow.yml
Add a single job to download (most of) the tarballs required. This
should allow the CI job to fail early when various sources are off-line
and prevent us from unintentionally DDoSing sites that we rely on.
=> CI: download tarballs

config/libc/glibc.in, scripts/build/libc/glibc.sh
Issue #1535
GCC 10 changed the default to -fno-common, which leads to a linking error in GLibc older than 2.30.
This change adds -fcommon cflag for the target GLibc versions <=2.29 and GCC >=10.
This change also adds additional cflags for the target GLibc to disable
new GCC11 checks that lead to compilation errors.
Signed-off-by: Nik Konyuchenko <spaun2002mobile@gmail.com>
=> Fix build of older Glibc using GCC >=10

scripts/functions
cdn.kernel.org automatically redirects to a geographically close mirror.
Make use of this instead of www.kernel.org or mirrors.edge.kernel.org.
While were at it make sure we use https.
=> CT_Mirrors: make use of kernel cdn

config/global/build-behave.in, scripts/build/binutils/binutils.sh, scripts/build/cc/gcc.sh, scripts/crosstool-NG.sh
The new `EXTRA_CXXFLAGS_FOR_BUILD` option allows to add flags specifically for the build c++ compiler.
Fixes #1549
=> Add EXTRA_CXXFLAGS_FOR_BUILD option

kconfig/Makefile.am
After commits 21095fab6 and acce58834, 'make dist-create-release' fails.
1. kconf_id.c is gone but it is still listed in EXTRA_DIST.
2. Only the files not listed in xxx_SOURCES need to be placed in
EXTRA_LIST. confdata.c, expr.c and others were previously not compiled
separately, they were #include'd from parser.y. Now they are listed in
xxx_SOURCES and should be removed from EXTRA_DIST. Note that menu.c is
still #include'd through parser.y, so it is kept.
3. parser.tab.c and lexer.lex.c should not be included in the
distribution tarball; they were previously omitted by virtue of not
being listed in xxx_SOURCES directly. Without it, `make distcheck`
fails.
Signed-off-by: Alexey Neyman <aneyman@lynx.com>
=> Fix dist-create-release after kconfig update

scripts/functions
This commit updates the patching process such that the local patches
can be applied in a version-independent manner, as with the patches
provided by the crosstool-ng packages.
This is done by reading the patch files from
`${CT_LOCAL_PATCH_DIR}/(package_name)` rather than from
`${CT_LOCAL_PATCH_DIR}/(package_name)/(version)`.
Signed-off-by: Stephanos Ioannidis <root@stephanos.io>
=> Support common local patch directory

.github/workflows/continuous-integration-workflow.yml
Various configurations end up using these companion tools (particularly
those with GNU libc). Ensure we download these tools at the start of the
build.
=> CI: Download bison, m4 and make

scripts/build/kernel/linux.sh
no-mmu architectures need to be explicitly listed
in CT_DoKernelTupleValues
Signed-off-by: Steve Bennett <steveb@workware.net.au>
=> Add support for no-mmu microblaze

scripts/build/arch/arc.sh
Older ARC700 processors had atomic instructions (AKA llock/scond) as an option and so quite some "atomic" operations were not possible w/o OS support, which we implemented - see `arc_usr_cmpxchg()` in the Linux kernel.
And in uClibc, which was the only Linux libc back in the day of ARC700 era, it is well supported. Well, uClibc could be configured to support it. Which is done with `CONFIG_ARC_HAS_ATOMICS` Kconfig option.
But the problem is there's no check for ARC ISA version in uClibc when this option gets enabled. That leads to a funny situation when even for ARCv2 processors (ARC HS3x & HS4x) uClibc tries to utilize `arc_usr_cmpxchg()` syscall which is not supported for this newer ISA since ARCv2 processors have atomic instructions built-in all the time.
So what was happening here we …
=> ARC: No more fiddling with uClibc's CONFIG_ARC_HAS_ATOMICS

config/cc/gcc.in, scripts/build/cc/gcc.sh
GCC can support using zstd compression for LTO object files. By default
GCC's configure will enable this if libzstd is installed on the machine
building the toolchain. This may be undesirable if the toolchain is to
be used on a different machine. Add an option to control zstd usage and
set the default to the same as the current behaviour (i.e. auto).
Fixes #1579
=> cc/gcc: Add options for zstd usage

scripts/build/cc/gcc.sh
`--with-host-libstdcxx` option was removed in GCC 6.x, see https://gcc.gnu.org/git/?p=gcc.git&a=commit;h=5dc85f7ec719a79ecfbcdd8563b07e5f0f365e65 because of https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67092.
So it makes no sense to use it with later GCC versions.
Frankly I don't like that implementation with yet another set of "if XXX", but since we still support GCC down to 4.8.5 what else we may do?
Well, technically we may keep using things as they are now, because surprisingly GCC's configure script doesn't mind accepting meaningless options, but as a person who's looking at differences between various builds and drill-down to peculiarities of various config options, I'd prefer to not pollute configure with garbage.
But for all the rest... well, it works now and maybe nobody else …
=> gcc: Don't mess with --with-host-libstdcxx if recent GCC (6+) is used

scripts/build/cc/gcc.sh
GCC 11+ requires compiler being used to support C++11 standard [1].
And while GCC starting from 6.x has C++11 support enabled by default [2], older versions need to be forced to implement it with "-std=gnu++11" and luckily GCC's build-system takes care of that:
1. For `${host}` compiler - [1]
2. For `${build}` compiler - [3, 4]
In a nutshell the configure script tries a couple of options and the one which helps to build a test source gets appended to `CXX` (not `CXXFLAGS`!), so on say CentOS 7.x with GCC 4.8.5 during cross-compilation of GCC `CXX=x86_64-build_pc-linux-gnu-g++ -std=gnu++11`. And all is good.
But in case of canadian cross due to [5] we for some reason (read-on) force set `CXX_FOR_BUILD` with just a compiler name, effectively overriding all the magic done by GCC's internals …
=> gcc: Fix canadian cross building on older hosts

packages/binutils/2.37/0009-arc-Fix-potential-invalid-pointer-access-when-fixing.patch
While building statically-linked executables for ARC on 32-bit platform LD segfaulted like that:
```
$ gcc test.c -static
potentially unexpected fatal signal 11.
Path: /arc_gnu_2021.03_prebuilt_glibc_le_archs_native_install/arc-snps-linux-gnu/bin/ld
CPU: 0 PID: 79 Comm: ld Not tainted 5.10.43 #8
Invalid Read @ 0x00000020 by insn @ 0x40bbe
@off 0x40bbe in [/arc_gnu_2021.03_prebuilt_glibc_le_archs_native_install/arc-snps-linux-gnu/bin/ld]  VMA: 0x00010000 to 0x0010e000
ECR: 0x00050100 EFA: 0x00000020 ERET: 0x00040bbe
STAT: 0x80080082 [IE U     ]   BTA: 0x0003fc24
SP: 0x5fdb8dec  FP: 0x00129598 BLK: 0x40b66
LPS: 0x2008c602 LPE: 0x2008c63e LPC: 0x00000001
r00: 0x008392f2 r01: 0x00000001 r02: 0x00000000
r03: 0x008392f2 r04: 0x00000058 r05: 0x00e37e88
r06: 0x00eb8ea8 r07: 0x00a837e8 r08: …
```
=> binutils 2.37: arc: Fix for 32-bit hosts

packages/binutils/2.37/0010-change-uint-to-unsigned.patch
This fixes a defect introduced in 25162c7. The "uint" type has not
been explicitly defined here on mingw, causing compilation to fail.
Signed-off-by: Artem Panfilov <artemp@synopsys.com>
=> binutils: Add MinGW build fix from 2.37 branch

scripts/build/debug/300-gdb.sh
Since we have curses built for target anyway now, why don't allow users to use very convenient pseudo-GUI operating mode?
And while at it, there's no use of TUI in naturally headless `gdbserver`.
=> gdb: Enable TUI for full target/native GDB

.github/workflows/continuous-integration-workflow.yml
The CI builds currently seem unhappy on macOS when we build make
ourselves. Install GNU make via brew so that we don't have to build it
ourselves.
=> CI: install the latest GNU make on macOS

packages/cloog/package.desc
The GNU mirror doesn't contain cloog-18.4. Remove it.
=> cloog: remove gnu mirror

.github/workflows/continuous-integration-workflow.yml
Add i686-w64-mingw32 and x86_64-w64-mingw32 to the targets built for CI.
=> CI: Add mingw32 samples

packages/gcc/11.2.0/0009-Darwin-aarch64-Initial-support-for-the-self-host-dri.patch
With latest aarch64-unknown-linux-gnu, ct-ng build failed with:
[INFO ]  Installing pass-1 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[ERROR]    clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR]    make[2]: *** [Makefile:2148: xgcc] Error 1
[ERROR]    make[2]: *** Waiting for unfinished jobs....
[ERROR]    clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR]    make[2]: *** [Makefile:2157: cpp] Error 1
[ERROR]    make[1]: *** [Makefile:4444: all-gcc] Error 2
And in build log:
Undefined symbols for architecture arm64:
"host_detect_local_cpu(int, char const**)", referenced from:
static_spec_functions in gcc.o
Just backport a upstream gcc fix.
Signed-off-by: Kairui Song …
=> gcc: Fix 11.2.0 build failure on MacOS with Apple M1

configure.ac
BSD patch does not support --no-backup-if-mismatch. When we detect patch
check that it supports the option we use.
Fixes: #1577
=> configure.ac: Check that patch supports --no-backup-if-mismatch

config/cc.in, config/libc/glibc.in, config/libc/moxiebox.in, config/libc/musl.in, config/libc/newlib.in, config/libc/uClibc.in, scripts/build/cc/gcc.sh
Per https://github.com/crosstool-ng/crosstool-ng/issues/808 build static
libgcc in the first pass which lets us skip the second one.
Very lightly tested at this point. Creating PR to make use of CI builds.
=> gcc: Build static libgcc in core_pass1

config/binutils/binutils.in
Versions before 2.26 got removed in fa992b41, together with
CT_BINUTILS_2_23_or_later.
Remove reference to this variable
Signed-off-by: Norbert Lange <nolange79@gmail.com>
=> Fix deterministic binutils option

packages/binutils/2.37/0011-bfd-close-the-file-descriptor-if-there-is-no-archive-fd.patch, packages/binutils/2.37/0012-pr28391-strip-objcopy-preserve-dates-a-cannot-set-time.patch, packages/binutils/2.37/0013-ld-pru-fix-resource_table-output-section-alignment.patch, packages/binutils/2.37/0014-pr28422-build_id-use-after-free.patch, packages/binutils/2.37/0015-pr28459-readelf-issues-bogus-warning.patch, packages/binutils/2.37/0016-pr28417-std-string-no-longer-allows-accepting-nullptr_t.patch, packages/binutils/2.37/0017-pr28540-segmentation-fault-on-NULL-byte_get.patch, packages/binutils/2.37/0018-gold-place-note-gnu-property-section-before-other-note-sections.patch, packages/binutils/2.37/0019-waddress-warning-in-ldelf.c.patch
Fetch in various patches from binutils-2_37-branch upstream.
The most vital change is the
0012-pr28391-strip-objcopy-preserve-dates-a-cannot-set-time.patch which
allows building large upstream projects like Qt WebEngine without need
100k's of file descriptors open.
Signed-off-by: Hans-Christian Noren Egtvedt <hegtvedt@cisco.com>
=> binutils-2.37: add more patches from upstream release branch

config/arch/powerpc.in
Support for the SPE ABI was removed in GCC 9. Update the select to
GCC_REQUIRE_older_than_9 so that GCC 8.5 can be selected.
Fixes #1349, fixes #1666
=> powerpc: Allow GCC 8.5 for SPE ABI

.github/workflows/build-toolchains.yml, .github/workflows/continuous-integration-workflow.yml
Add reusable GitHub workflow to build Canadian Cross toolchain where
the x86_64-w64-mingw32 cross-compiler is used which is built with ct-ng.
Signed-off-by: Artem Panfilov <artemp@synopsys.com>
=> CI: add Canadian Cross build job

packages/glibc-ports/2.12.1/version.desc, packages/glibc/2.12.1/version.desc
CentOS6 has reached EOL so now glibc-2.12.1 can be marked as obsolete.
This also means the last glibc-ports version (and glibc-ports itself)
obsolete as well. These will be removed after the next release.
=> glibc: mark 2.12.1 as obsolete

scripts/build/binutils/binutils.sh
libdebuginfod is incompatible with static linking so pass
--without-debuginfod when CT_STATIC_TOOLCHAIN is selected.
Fixes #1683
=> binutils: Disable libdebuginfod when producing a static toolchain

config/cc/gcc.in, scripts/build/cc/gcc.sh
Rather important option for arm cortex toolchains supporting c++,
avoids pulling in all printf/iostream code by default.
=> gcc: add gcc libstdcxx-verbose option

packages/gcc/11.2.0/0010-libstdc-Check-for-TLS-support-on-mingw-cross-compile.patch
Backport of https://github.com/gcc-mirror/gcc/commit/cc1e28878a228b6c4a0872e56d97ac88971b7725
=> Fix MinGW libstdc++ TLS functionality

kconfig/lxdialog/dialog.h, kconfig/nconf.h
Prior to commit bbc4db13 ("kconfig: Sync with upstream v4.18") we used
the macro CURSES_LOC to tell us where curses.h was installed. Restore
this behaviour so that we can deal with some of the odd places curses.h
ends up.
Fixes #1403
=> kconfig: Use ncurses location determined by ./configure

packages/binutils/2.38/0008-binutils-2.38-vs.-ppc32-linux-kernel.patch, packages/gcc/10.3.0/0023-powerpc-Fix-asm-machine-directive-for-some-CPUs.patch, packages/gcc/11.2.0/0010-powerpc-Fix-asm-machine-directive-for-some-CPUs.patch
Some versions of GCC emit a .machine directive near the start of the
compiler's assembly output that overrides the CPU passed on the command
line. Bring in an upstream change for binutils that works around the
problem.
=> binutils: Bring in upstream fix for powerpc

config/arch/xtensa.in
Just a minor fix, to be consistent in names and comments
=> xtensa: Remove obsoleted CT_ARCH_XTENSA_CUSTOM_NAME

testing/docker/fedora35/Dockerfile, testing/docker/mint20-amd64/Dockerfile, testing/docker/ubuntu18.04/Dockerfile, testing/docker/ubuntu21.10/Dockerfile
meson and ninja are needed to build picolibc.
=> testing/docker: Add meson and ninja to containers

scripts/functions
On my Ubuntu machine (with `dash` version `0.5.10` and `bash` version `5.0.17`), I would get errors such as the following:
```
crosstool-ng/scripts/functions: line 730: [: !=: unary operator expected
```
This is generally because a variable is not set, and expands to an empty string causing the test operator to mis-parse the expression.  To fix this, I have added quotes around the variable.
=> [scripts/functions]: Fix quoting issue in comparison

config/libc/glibc.in, packages/glibc/package.desc
Newer GCC versions trigger warnings on older GLIBC versions. GLIBC 2.29
is warning free with GCC9. GLIBC 2.31 is warning free with GCC10. GLIBC
2.34 is warning free with GCC11.
Add milestones for 2.31 and 2.34 and use those to set the default value
for GLIBC_ENABLE_WERROR based on the GCC version.
=> glibc: Enable -Werror for more combinations of GCC/GLIBC

scripts/populate.in
Modern versions of the `file` utility give different output for position
dependent and position independent executables. The populate tool should
consider both types.
Versions of file prior to February 2018 (e.g. Debian Stretch) would report PIE executables as `executable`. Versions between February 2018 and February 2020 (e.g. Debian Buster) would identify them as `shared object`. Modern versions (e.g. Debian Bullseye) idenentify PIE executables as `pie executable`.
Signed-off-by: Johan Levin <johan13@gmail.com>
=> populate: Include dependencies of PIE executables

scripts/build/companion_libs/350-newlib_nano.sh
With 'CT_NEWLIB_NANO_INSTALL_IN_TARGET=y', this build failure occurs:
````
[...]
[INFO ]  Installing Newlib Nano library
[EXTRA]    Configuring Newlib Nano library
[EXTRA]    Building Newlib Nano C library
[EXTRA]    Installing Newlib Nano C library
[INFO ]  Installing Newlib Nano library: done in 110.66s (at 29:04)
[INFO ]  =================================================================
[INFO ]  Installing libstdc++ newlib-nano
[EXTRA]    Configuring libstdc++ for newlib-nano
[EXTRA]    Building libstdc++ newlib-nano library
[EXTRA]    Installing libstdc++ newlib-nano library
[EXTRA]    Housekeeping for core gcc compiler
[EXTRA]       '' --> lib (gcc)   lib (os)
[EXTRA]       ' -mthumb' --> lib/thumb (gcc)   lib/thumb (os)
[EXTRA]       ' -marm -mfpu=auto -march=armv5te+fp …
```
=> scripts/build/companion_libs: Fix missing directory with newlib-nano

scripts/build/companion_libs/350-newlib_nano.sh
When `CT_NEWLIB_NANO_INSTALL_IN_TARGET=y`, the `nano.specs` file
emitted by the newlib-nano build script contains an invalid include
path, resulting in the full `newlib.h` being included instead of the
nano `newlib.h` by the application.
`=/include/newlib-nano` is not a valid path (`=` does not mean anything
and that string is taken as an include path as-is) and GCC ignores this
include path, resulting in application including the `newlib.h` from
`include/` which contains the newlib build configurations for the full
newlib.
This commit modifies the newlib-nano build script to emit a proper
newlib-nano include path relative to the `GCC_EXEC_PREFIX`.
Signed-off-by: Stephanos Ioannidis <root@stephanos.io>
NOTE: This `nano.specs` file was originally taken from the GNU Arm Embedded toolchain. …
=> newlib-nano: Fix include path for CT_NEWLIB_NANO_INSTALL_IN_TARGET

maintainer/manage-packages.sh
The unified diff patch format will contain slightly more information,
which is helpful when rebasing patches to new releases.
Signed-off-by: Hans-Christian Noren Egtvedt <hegtvedt@cisco.com>
=> Create unified diff when refreshing patch files in manage-packages.sh

config/libc/glibc.in, scripts/build/libc/glibc.sh
Commit 6d5227b6 ("Remove obsolete glibc 2.12.1") removed supports for
the separate glibc-ports but also removed GLIBC_USE_PORTS_ADDON. Glibc
versions up to 2.20 bundled support from some architectures in the ports
directory so GLIBC_USE_PORTS_ADDON is required to support these older
glibc versions.
Fixes #1736
=> glibc: Reinstate support for the bundled ports

packages/gcc/11.3.0/0010-libsanitizer-mips64-Set-struct_kernel_stat_sz-to-mat.patch
The kernel's struct stat is 104 bytes when compiling for
_MIPS_SIM_ABI64. Set struct_kernel_stat_sz to match.
Fixes #1733
=> gcc: Bring in fix for libsanitizer on mips64

packages/glibc/2.23/0014-MIPS-SPARC-fix-wrong-vfork-aliases-in-libpthread.so.patch
glibc-2.23 fails to build for mips with
nptl/libpthread.so:(*IND*+0x0): multiple definition of `vfork@GLIBC_2.0';
This was fixed in glibc-2.24. Backport the fix for glibc-2.23.
Fixes #1744
=> glibc: backport fix for vfork on mips

config/libc/glibc.in
Use `depends on` conditions to enable/disable building glibc with
-Werror. Using `depends on` instead of `default if` means that when the
GCC/GLIBC selection changes GLIBC_ENABLE_WERROR will automatically
become n.
Fixes #1729, fixes #1712
=> glibc: rework GLIBC_ENABLE_WERROR

scripts/build/companion_libs/100-gmp.sh
When GMP is being "cross" compiled for the same architecture (i.e. build
== host) it does not pick the right compiler. Set CC_FOR_BUILD and
CPP_FOR_BUILD to override the default compiler.
Fixes #1328
=> gmp: Set CC_FOR_BUILD and CPP_FOR_BUILD

config/cc/gcc.in
We don't currently bundle zstd so when performing a canadian build we
need to tell GCC not to enable zstd support for lto otherwise it might
decide to enable it based on the package being installed on the build
machine.
Fixes #1718
=> gcc: Disable zstd for canadian builds

scripts/build/cc/gcc.sh
When core gcc older than v5 is compiled it shows the error message:
Build failed in step 'Installing core C gcc compiler'
called in step '(top-level)'
Error happened in: CT_DoExecLog[scripts/functions@376]
called from: do_gcc_core_backend[scripts/build/cc/gcc.sh@627]
called from: do_cc_core[scripts/build/cc/gcc.sh@210]
called from: main[scripts/crosstool-NG.sh@697]
configure: error: in
`.../build/build-cc-gcc-core/fixincludes':
configure: error: C compiler cannot create executables
This patch disable `all-build-libcpp' target when core gcc
older than v5 is configured.
Signed-off-by: Guillermo E. Martinez <guillermo.e.martinez@oracle.com>
=> gcc: Fix compilation error in core C gcc compiler older than v5

configure.ac
Make the requirement for bison harder (but not strict). The system bison
will be used to build kconf. If the system bison is not GNU bison 2.7 or
later crosstool-ng will build GNU bison as a companion tool if necessary
(for glibc 2.29 or newer).
Fixes #1621
=> configure.ac: bison is required for kconf

config/cc.in, config/cc/gcc.in, scripts/build/cc/gcc.sh
Enable D support as an experimental feature.
GDC becomes a build dependency when enabled.
Signed-off-by: Marc Poulhiès <dkm@kataplop.net>
=> Enable D language support

bootstrap
Tabs or spaces... I believe the policy on ct-ng is spaces for shell
scripts. So update bootstrap to stick to 4 space indent.
=> Fix mixed indent in bootstrap

scripts/build/cc/gcc.sh, scripts/crosstool-NG.sh
CT_CC_{CORE_}SYSROOT_ARG is being used both as an array and string. Switch everything
to be used as an array for consistency.
Signed-off-by: Justin Chen <justinpopo6@gmail.com>
=> Switch CT_CC_{CORE_}SYSROOT_ARG to arrays

config/cc/gcc.in, scripts/build/cc/gcc.sh
Make it proper "tristate" by not specifying the
option.
The config GCC_4_8_or_later was removed with
cc6b7fad46f5cb3d84, so dont use it.
=> Fixes for libstdcxx-verbose option tristate

.github/workflows/continuous-integration-workflow.yml
Add x86_64-w64-mingw32 to the list of samples we use to fetch sources.
This should pick up the mingw related tarballs so the build steps that
follow don't have to.
=> CI: Add fetch mingw sources

.github/workflows/build-toolchains.yml, .github/workflows/continuous-integration-workflow.yml
Add meson and ninja-build to the prerequisites so we actually build
picolibc.
=> CI: Install meson and ninja when building

configure.ac
It appears that noyywrap is actually what is needed for kconfig.
Particularly on arclinux where the default flex installation does not
provide the yywrap function.
Fixes #1790
Fixes 015d039e ("AC_PROG_LEX set to yywrap")
=> configure.ac: AC_PROG_LEX set to noyywrap

.github/workflows/build-toolchains.yml, .github/workflows/continuous-integration-workflow.yml
Update the CI actions from macos-10.15 to macos-latest.
=> CI: Update to macos-latest

samples/arm-none-eabi/crosstool.config
This warning is designed to catch likely vulnerabilities in code run
under memory protection -- allowing execution from memory which is
writable. However, embedded arm systems frequently require placing code
in RAM, for performance or functionality reasons. Disable the warning
that recent versions of binutils has added.
Signed-off-by: Keith Packard <keithp@keithp.com>
=> arm-none-eabi: Disable RWX segment warning in binutils

scripts/build/cc/gcc.sh
`${CT_PREFIX_DIR}` may contain relative paths (e.g.
`"${CT_TOP_DIR}/../x-tools/${CT_TARGET}"`). Code added in commit d83a0036 ("Add symlinks from the libraries' original location to the new one.") didn't cope well with this. As we're already calculating `${cannon_prefix}` make use of it when adding the symlinks. This avoids any issues with `${CT_PREFIX_DIR}`.
Fixes #1807
=> cc/gcc: Use canon_prefix when dealing with moved libraries

config/cc/gcc.in
PIE is not supported by PRU and AVR backends for GCC.
This fixes LD errors when trying to link user programs with a crosstool-NG toolchain:
/home/dinux/x-tools/avr/lib/gcc/avr/12.2.0/../../../../avr/bin/ld: -pie not supported
collect2: error: ld returned 1 exit status
Signed-off-by: Dimitar Dimitrov <dimitar@dinux.eu>
=> avr,pru: Disable CT_CC_GCC_ENABLE_DEFAULT_PIE

config/binutils/binutils.in, scripts/build/binutils/binutils.sh
Add an option to build and install binutil's libopcodes into the toolchain.
Setting the default to 'y' like in the libbfd and libiberty options, not sure if that is ok.
=> Build libopcodes for target

scripts/crosstool-NG.sh
Add gdc to the tool list but leave it optionnal.
Signed-off-by: Marc Poulhiès <dkm@kataplop.net>
=> Add the gdc compiler to the list of tools checked/linked

.github/workflows/build-toolchains.yml, .github/workflows/continuous-integration-workflow.yml
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Update to v3 version of affected actions.
=> CI: Update action versions

config/cc.in
Ada is a name, not an acronym, so it doesn't need to be up-cased.
Signed-off-by: Marc Poulhiès <dkm@kataplop.net>
=> Correct casing for Ada lang

.github/workflows/build-toolchains.yml, packages/glibc/2.36/0006-Makerules-fix-MAKEFLAGS-assignment-for-upcoming-make.patch
Add an upstream patch that resolves a compatibility issue with GNU make 4.4.
Fixes #1858
=> glibc: Add fix for GNU make 4.4 compatibility issue

scripts/functions
If a user deletes the package directory under `.build/src/` but fails to remove the hidden stamp files the CT_DoExtractPatch function will detect this, delete the stamps and perform the full extract-and-patch step.
=> Detect if a package src_dir is missing

packages/newlib-nano/package.desc, packages/newlib/package.desc
Some corporate VPN services block ftp connections. It leads to an error while building a toolchain with packages with ftp mirrors. It's possible to safely use https instead of ftp.
Signed-off-by: Yuriy Kolerov <ykolerov@synopsys.com>
=> Change ftp mirror link for newlib packages to https one

m4/ax_with_curses_extra.m4
Should fix #1853
Reverts the changes introduced to `m4/ax_with_curses_extra.m4` in 59b664806c55dc1e5878448be2536fe110944f62, which seem to make `cofigure` look only for `ncursesw/panel.h` and not consider `panel.h` as a candidate, thus causing `./configure --with-ncurses` to fail with "error: panel library not found" on systems (such as Arch Linux) where ncurses headers are not put under the `ncursesw/` directory.
=> Fix `./configure --with-ncurses` not working on Arch Linux

config/cc/gcc.in
-pie is not supported on riscv*-elf-ld so having this configuration switch enabled for these targets causes issues later when we try to use the target compiler.
References: 
- https://github.com/bminor/binutils-gdb/blob/13556f4057d37f510f77143a1632febcc5618d1f/ld/lexsup.c#L1303-L1313
- https://github.com/bminor/binutils-gdb/blob/13556f4057d37f510f77143a1632febcc5618d1f/ld/emultempl/elf.em#L84
- https://github.com/bminor/binutils-gdb/blob/13556f4057d37f510f77143a1632febcc5618d1f/ld/emulparams/elf32lriscv-defs.sh#L19-L27
=> gcc: Disable CC_GCC_ENABLE_DEFAULT_PIE on RISC-V bare metal builds

config/cc.in, config/cc/gcc.in, scripts/build/cc/gcc.sh, scripts/build/companion_libs/050-zlib.sh, scripts/build/companion_libs/100-gmp.sh, scripts/build/companion_libs/110-mpfr.sh, scripts/build/companion_libs/121-isl.sh, scripts/build/companion_libs/130-cloog.sh, scripts/build/companion_libs/140-mpc.sh
libgccjit is still under development and, despite its name, may also be used for ahead-of-time compilation.
Documentation can be found on the gcc website:
https://gcc.gnu.org/onlinedocs/jit/internals/index.html https://gcc.gnu.org/wiki/JIT
With this change it's possible to enable the building of the libgccjit. It's enabled as a language (with --enable-languages=jit) even if not a language frontend at all.
The main changes are related to the requirement of having everything host side built as Position Independent Code (PIC) with --enable-host-shared. GCC has the needed logic for building its dependencies (mpc, gmp, mpfr, ...) correctly when built "in-tree", which is not the case with crosstool-ng (see https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=05048fc29f0)
Signed-off-by: Marc Poulhiès …
=> Enable support for building libgccjit

packages/glibc/2.26/0006-Makerules-fix-MAKEFLAGS-assignment-for-upcoming-make.patch, packages/glibc/2.27/0002-Makerules-fix-MAKEFLAGS-assignment-for-upcoming-make.patch, packages/glibc/2.28/0003-Makerules-fix-MAKEFLAGS-assignment-for-upcoming-make.patch, packages/glibc/2.29/0004-Makerules-fix-MAKEFLAGS-assignment-for-upcoming-make.patch, packages/glibc/2.30/0004-Makerules-fix-MAKEFLAGS-assignment-for-upcoming-make.patch, packages/glibc/2.31/0003-Makerules-fix-MAKEFLAGS-assignment-for-upcoming-make.patch, packages/glibc/2.32/0003-Makerules-fix-MAKEFLAGS-assignment-for-upcoming-make.patch, packages/glibc/2.33/0003-Makerules-fix-MAKEFLAGS-assignment-for-upcoming-make.patch, packages/glibc/2.34/0002-Makerules-fix-MAKEFLAGS-assignment-for-upcoming-make.patch, packages/glibc/2.35/0003-Makerules-fix-MAKEFLAGS-assignment-for-upcoming-make.patch
Backport the upstream fix for GNU make 4.4 compatibility to more versions of glibc.
Fixes #1878
=> glibc: Add fix for GNU make 4.4 compatibility to more versions

config/global/paths.in, scripts/build/internals.sh
Add TARBALL_RESULT option that will produce a tarball of the final
toolchain to make it easier to deploy the toolchain to other machines.
The implementation uses `find | sort` instead of `tar --sort` because
this was introduced in GNU Tar v1.28, which is not available in some LTS
Linux distributions. This is  a variation of the command recommended
here: https://wiki.debian.org/ReproducibleBuilds/FileOrderInTarballs
Closes #1262
=> Add option to build toolchain tarball

.github/workflows/build-toolchains.yml
Update some hard coded names to use ${{ matrix.sample }} instead. This will allow us to upload other artifacts in the future.
=> CI: Use ${{ matrix.sample }} when uploading artifacts

config/cc/gcc.in
This changes how existing crosstool-ng setups work, causing many of the bare-metal ones to fail.
Closes: #1900
=> gcc: Don't set --enable-default-pie by default

.github/workflows/build-toolchains.yml
The arm-picolibc-eabi build runs out of space on the macos makers because of all the multilib permutations. For now disable the macos,arm-picolibc-eabi combination until we can think of something better.
=> CI: Exclude macos,arm-picolibc-eabi combination

packages/gcc/6.5.0/0031-darwin-aarch64-config.patch, packages/gcc/6.5.0/0032-darwin-aarch64-self-host-driver.patch, packages/gcc/6.5.0/0033-darwin-align-pch_address_space-to-16k.patch, packages/gcc/7.5.0/0021-darwin-aarch64-config.patch, packages/gcc/7.5.0/0022-darwin-aarch64-self-host-driver.patch, packages/gcc/7.5.0/0023-darwin-align-pch_address_space-to-16k.patch, packages/gcc/8.5.0/0023-darwin-aarch64-config.patch, packages/gcc/8.5.0/0024-darwin-aarch64-self-host-driver.patch, packages/gcc/8.5.0/0025-darwin-align-pch_address_space-to-16k.patch, packages/gcc/9.5.0/0019-darwin-aarch64-config.patch, packages/gcc/9.5.0/0020-darwin-aarch64-self-host-driver.patch
Ported from https://github.com/richfelker/musl-cross-make/pull/129
=> Support targeting macOS aarch64 in older GCCs

config/arch/x86.in
GCC's libsanitizer module does provide a subset of support for x86 targets (e.g. libasan). GCC's `libsanitizer/configure.tgt` file only outlines flags for optional sanitizers.
=> config/arch/x86: enable libsanitizer

packages/gdb/13.1/0000-gdbserver-linux-low.cc-Fix-a-typo-in-ternary-operato.patch
On systems that lack pread64() (e.g. musl) the following build error is observed.
src/gdb/gdbserver/linux-low.cc:5393:45: error: expected ':' before ')' token
src/gdb/gdbserver/linux-low.cc:5393:45: error: expected primary-expression before ')' token
src/gdb/gdbserver/linux-low.cc:5393:45: error: expected ':' before ')' token
src/gdb/gdbserver/linux-low.cc:5393:45: error: expected primary-expression before ')' token
Bring in the upstream fix for this error.
=> gdb: Bring in upstream fix for build error

scripts/build/debug/300-gdb.sh
Variable ``native_extra_config`` must be used for configuration options instead for ``extra_config`` for native GDB.
=> gdb: Fix extra config variable name for native GDB

config/comp_libs.in, config/debug/gdb.in.native, scripts/build/companion_libs/110-mpfr.sh
Add support of building MPFR for target and make GDB 13+ dependent on MPFR in any case (while GDB building for host or for target) because MPFR is mandatory for GDB 13+.
=> Add support of building MPFR for target and make GDB 13+ dependent on MPFR

scripts/build/debug/300-gdb.sh
Use a relative path for include directory if `gdb` or `gdbserver` is being built and installed for a target. Otherwise headers are installed in `${destdir}${CT_HEADERS_DIR}` - a concatenation of `${destdir}` and an absolute path to sysroot's include directory. As a result `debug-root` may contain wrong paths for includes.
=> gdb: Use a relative includedir for native gdb and gdbserver

scripts/build/debug/300-gdb.sh
This change makes linking cross GDBstatically with std c++ library if statis build is selected (because there is no separate option for std c++ lib for cross GDB). Also fixes usage of not existing variable CT_GDB_NATIVE_STATIC_LIBSTDC, by replacing it with CT_GDB_NATIVE_STATIC_LIBSTDCXX
=> gdb: Static cross GDB is linked statically with std c++ library

packages/newlib/4.1.0/0002-minimal-support-for-ts-18661-3.patch, packages/newlib/4.1.0/0003-support-__FLT_EVAL_METHOD__-values.patch
Bring in upstream support for newer float standards being used by GCC.
Fixes #1957
=> newlib: Add upstream patches for float support

config/libc/mingw-w64.in, scripts/build/libc/mingw-w64.sh
This also addresses issue #1896.
I wasn't sure if I should make this just a bool for ucrt, a selection of the known list, or just a free-form text.
In the end, I decided for a plain string, since it gives users the most flexibility.
=> Add default msvcrt options for mingw-w64

packages/strace/6.3/0000-configure-do-not-take-the-SUBLEVEL-part-of-the-kerne.patch
In the rush to sort out a build issue with strace an invalid change to ./configure was made. Update the patch with the correct delta for the generated file.
Fixes #1978
Fixes: d659700d ("strace: Add strace 6.3")
=> strace: Fixup patch to configure

config/cc/gcc.in, samples/riscv64-multilib-elf/crosstool.config, samples/riscv64-multilib-elf/reported.by, scripts/build/cc/gcc.sh
To build multilib RISC-V toolchain one should use --with-multilib-generator option instead of --with-multilib-list.
Add corresponding example configuration file.
=> Properly build multilib bare-metal RISC-V

config/configure.in.in, configure.ac
This reverts commit 658f5e574f4025655da318fb0b688a394b6ff43f, which was made without any justification, and prevents using crosstool-ng even in decently recent distributions like Ubuntu 20.04 (which has autoconf 2.69).
We have tested that ./bootstrap && ./configure --enable-local works fine on Ubuntu 18.04, which uses autoconf 2.69 and automake 1.15, so the existing requirements were enough.
=> Revert "Update requirements: autoconf==2.71 and automake>=1.16"

packages/newlib/2.5.0.20171222/version.desc, packages/newlib/3.0.0.20180831/version.desc, packages/newlib/3.1.0.20181231/version.desc, packages/newlib/3.2.0/version.desc, packages/newlib/3.3.0/version.desc, packages/newlib/4.1.0/version.desc
Mark newlib 2.5.0.20171222, 3.0.0.20180831, 3.1.0.20181231, 3.2.0, 3.3.0 and 4.1.0 as obsolete. These can be dropped after the next crosstool-ng release.
=> newlib: Mark versions <= 4.1.0 as obsolete

packages/newlib/2.5.0.20171222/version.desc, packages/newlib/3.0.0.20180831/version.desc, packages/newlib/3.1.0.20181231/version.desc, packages/newlib/3.2.0/version.desc, packages/newlib/3.3.0/version.desc, packages/newlib/4.1.0/version.desc
The missing quotes affect bootstrap routine:
./bootstrap: eval: line 646: unexpected EOF while looking for matching `'' ./bootstrap: eval: line 647: syntax error: unexpected end of file
For some reason bootstrap script ignores these errors and terminates successfully.
=> Fix missing quote mark

bootstrap
newlib-nano package shares patches with newlib package via symlinks. If a user chooses local setup (--enable-local) it works perfectly, but if a user chooses normal setup (make install), the links are lost.
=> bootstrap: follow symlinks

packages/ncurses/6.0/0013-Improve-version-extraction.patch, packages/ncurses/6.1/0001-Improve-version-extraction.patch, packages/ncurses/6.2/0000-Improve-version-extraction.patch
On canadian cross build-gcc reports its version as '13-win32'. ncurses >=6.3 correctly interprets this line as '13', but older ncurses versions fail and jump into wrong conclusions.
Let's cherry-pick related changes from mainline ncurses.
=> ncurses: correctly parse sofisticated gcc version

scripts/build/debug/300-gdb.sh
For mingw host a special macro NCURSES_STATIC must be defined.
=> gdb: fix build with recent ncurses

packages/gcc/13.2.0/0011-libsanitizer-Remove-crypt-and-crypt_r-interceptors.patch
libsanitizer has problems intercepting crypt() and crypt_r() with newer glibcs. Bring in an upstream patch that drops support for these from ASAN.
https://github.com/llvm/llvm-project/commit/d7bead833631486e337e541e692d9b4a1ca14edd https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111057
Fixes #2010
=> gcc: Add patch to resolve libsanitizer build issue

Makefile.am
The folder 'packages' is processed in bootstrap, so there is no need to process it again in Makefile.
This fixes a regression introduced in eb62ec3fbe3982f5f16561675fd0820d4313a0b4
=> Do not process 'packages' folder twice

config/libc/glibc.in, scripts/build/libc/glibc.sh
As of glibc-2.38 libcrypt is not built by default. Add an option to allow building libcrypt support into glibc.
=> glibc: Add option for building libcrypt

packages/gcc/13.2.0/0012-libgcc-m68k-Fixes-for-soft-float.patch
Here's a patch I've sent upstream which fixes a range of floating point bugs in libgcc.
=> gcc/13.2.0: Add patch with fixes for m68k soft float code

packages/glibc/2.38/0001-aarch64-configure-Pass-mcpu-along-with-march-to-dete.patch
glibc-2.38 requires SVE in order to support the vector math library for AArch64.
=> glibc: Fix SVE detection on aarch64

packages/gcc/13.2.0/0013-libgcc-Exclude-UCLIBC-from-GLIBC-thread-check.patch
A toolchain uclibc-ng-1.0.43, binutils-2.40 and gcc-13.2.0 hits the following error when building:
ld.bfd: isl_test2.o: non-canonical reference to canonical protected function `__pthread_key_create' in x86_64-multilib-linux-uclibc/sysroot/lib64/libc.so.1
ld.bfd: failed to set dynamic section sizes: bad value
Removing the protected attribute from __pthread_key_create seems to resolve the issue.
=> uClibc-ng: issues with __pthread_key_create

scripts/crosstool-NG.sh
older binutils dont automatically pick up plugins,
but need to manually use wrappers like gcc-ar.
This fix allows to compile the host toolchain with -ftlo
on debian stretch.
=> fix toolchain build with linker plugins

config/libc/musl.in, scripts/build/libc/musl.sh
I am not really familiar with bash arrays, please check usage.
Also I noted no c-library apparently sets target ldflags?
=> Make musl build use CT_TARGET_CFLAGS

config/binutils/binutils.in, config/cc/gcc.in
I was able to build a static toolchain that supports LTO by disabling these restrictions. Based on the original commits, it seems that this was a temporary limitation of the toolchain build and separately of Arch. I tested this with an arm-none-eabi target on Debian Bookworm.
https://github.com/crosstool-ng/crosstool-ng/commit/0841e2f820de7a4dca1
https://github.com/crosstool-ng/crosstool-ng/commit/45512b003d04b5a89c5
=> allow plugins and LTO with static toolchains

.github/workflows/build-toolchains.yml, .github/workflows/continuous-integration-workflow.yml, scripts/functions
more specificaly to the tarballs download. The function CT_Fetch now
touches the already existing files to be comparable to the not used ones
that can araise when a package is updated.
This comparsion is needed because if it would not exist the tarball
would grow in size due to not used but still cached packages.
This would take time but is definitly something to worry about.
Signed-off-by: Quentin Boswank <qubos@outlook.de>
=> Add more caching to the CI

scripts/build/debug/300-gdb.sh
Starting from GDB 11.x, gmp is needed as a dependency to build full gdb. And by default build system of native GDB will try to link with libgmp of the build host. And to make sure that doesn't happen we need to specify location of the target's sysroot so that library search starts from there. Which we do in that change.
Fixes [1] & [1].
[1] https://github.com/crosstool-ng/crosstool-ng/issues/2084
[2] https://github.com/crosstool-ng/crosstool-ng/issues/1656
=> gdb: Explicitly point to target's libgmp for native build

packages/glibc/2.17/0070-x86_64-Correct-THREAD_SETMEM-THREAD_SETMEM_NC-for.patch
This patch resolves compilation issues with GCC versions 12 and glibc 2.17.
It corrects the constraints used in the THREAD_SETMEM and THREAD_SETMEM_NC macros for the movq instruction
in the x86_64 architecture.
Backported from:
https://github.com/bminor/glibc/commit/b1ec623ed50bb8c7b9b6333fa350c3866dbde87f
Closes #1825
=> glibc: Fix THREAD_SETMEM/THREAD_SETMEM_NC for movq in x86_64

scripts/build/binutils/binutils.sh
This reverts commit 57f59092852dff18fbda68fdbf23f850ad182c40. This was originally added so that a toolchain could be built on a newer system but run on an older one. With the benefit of hindsight that is probably the wrong approach. The best way of achieving that goal would be to use docker/podman container to provide an environment that is the same as the oldest supported system and build inside that. The resulting toolchain should be compatible with the old system and the new one.
Closes #2094
=> Revert "binutils: Disable glob for better portability"

scripts/build/debug/300-gdb.sh
Similar to commit 65e5960a ("gdb: Fix extra config variable name for native GDB") we need to use cross_extra_config for the options we're passing to the gdb build when cross compiling.
Fixes: 5463ab4b ("gdb: Add gdb-10.2")
=> gdb: Fix extra config variable name for cross GDB

scripts/build/libc/glibc.sh
macos silicon SDK does not contain stat64 (and other LFS extension), and glibc 2.19 makes use of it.
glibc 2.17 with gcc 13 is OK without this fix, but I am not sure of other versions of glibc. But this change should be harmless generally.
=> glibc: fix the broken build for glibc 2.19 with gcc 13.

configure.ac
We use bash 4 features in some scripts
Signed-off-by: Quentin Boswank <qubos@outlook.de>
Fixes #2115
=> Check for bash version 4 or higher

packages/gcc/13.2.0/0033-LoongArch-Fix-MUSL_DYNAMIC_LINKER.patch, packages/gcc/13.2.0/0034-LoongArch-Modify-MUSL_DYNAMIC_LINKER.patch, packages/gcc/13.2.0/0035-LoongArch-Use-lib-instead-of-lib64-as-the-library-se.patch
This patch adds two gcc commits to fix musl libdir path for loongarch64:
* 13c5de14 ("LoongArch: Fix MUSL_DYNAMIC_LINKER")
* a5f1bdfc ("LoongArch: Modify MUSL_DYNAMIC_LINKER.")
* 2f7d4728 ("LoongArch: Use /lib instead of /lib64 as the library search path for MUSL.")
=> gcc/13.2.0: Fix musl libdir path for loongarch64

.github/workflows/continuous-integration-workflow.yml
We're currently hitting some disk space limits in the CI builds when building a canadian cross configuration
=>  CI: Disable canadian-cross build step

scripts/build/debug/300-gdb.sh
The native gdb needs the version of libexpat built for the target. On some systems gdb's configure will find the one from the build machine. Use --with-expat= to point at the correct one for the target.
Fixes: 2092
=> gdb: Use correct libexpat for native build

.github/workflows/build-toolchains.yml, .github/workflows/continuous-integration-workflow.yml
* Run `apt-get update` before installing packages, as the local VM may not have these packages already installed like the github.com runners do.
* Add bison, flex, and texinfo, as they may not already be on the local VM as they may be on the github.com runners.
=> Updates to github workflows to work with `gh act`

scripts/functions
Code added to deal with --enable-local used the non-existent CT_Error instead of CT_Abort. Use the correct function so the build aborts with a useful error message.
Fixes #2141
=> scripts/functions: Use CT_Abort when paths.sh is missing

scripts/build/libc/mingw-w64.sh
Wildcard is an opt-in (disabled by the default) feature that is used by many GNU tools like Binutils.
Signed-off-by: Mateusz Mikuła <mati865@gmail.com>
=> mingw-w64: enable wildcard

.github/workflows/build-toolchains.yml, .github/workflows/continuous-integration-workflow.yml
macos-latest has recently (as of April 2024) started transitioning to macos-14 (previously it was macos-12). This seems to be missing things we rely on (e.g. makeinfo) and even when those are added throws other errors.  For now lets pin things to macos-12 until someone can spend some time looking at why we can't use macos-14.
=> CI: pin macos runners to macos-12

packages/libelf/0.8.13/0001-fix-configure-for-gcc14.patch
Fixes a typo introduced in d97a1ecdf0058251c33f6e98ee30d0ca9c93d6ab.
=> Fix typo retrun→return in 0001-fix-configure-for-gcc14.patch

config/cc.in, scripts/build/cc/gcc.sh
Both D and GNAT have their own runtimes (resp. libphotos and libada). It is still possible to build the compiler proper without any runtime, and have an external runtime installed later. This is most commonly found in embedded systems.
An example for D is: https://github.com/KitsunebiGames/tinyd-rt
An example for Ada: https://github.com/Fabien-Chouteau/bare_runtime
=> Allow for Runtime-less build of GDC and GNAT

scripts/functions
Add https mirror for sourceware.org. Use https instead of http for kernel.org and gnu.org.
=> scripts/functions: Update sourceware mirrors

packages/gettext/0.22.5/0001-ctime-localtime-tzset-wcsftime-Fix-env-access-regr.-.patch
Cherry-pick the following commit from gnulib:
ctime, localtime, tzset, wcsftime: Fix env access (regr. 2024-02-09).
https://git.savannah.gnu.org/gitweb/?p=gnulib.git;a=commit;h=92cdf62b56462b914193c7770440e505a37c2526
This upstream patch fixes the following error:
[ERROR]    .../.build/HOST-x86_64-w64-mingw32/pru-elf/src/gettext/gettext-tools/gnulib-lib/localtime.c:66:24: error: initialization of 'char *' from incompatible pointer type 'char **' [-Wincompatible-pointer-types]
[ALL  ]       66 |         for (char *s = env; *s != NULL; s++)
Crosstool configuration:
build:  x86_64-unknown-linux-gnu
host:   x86_64-w64-mingw32
target: pru-elf
=> gettext: Fix cross build for mingw

scripts/functions, scripts/toolchain-config.in
Since commit 16c6cc99 ("Save the toolchain configuration to its own file, as an auto-extracting shell script:") we've been saving the configuration as a self extracting script. This is a little non-obvious as it looks like it should be a regular file but the bzipped payload means it can be easily inspected. It may also cause alarm for users who should rightly be suspicious of unexpected binaries that get shipped along with packaged toolchains. It also assumes that bzip2 (or at least bzcat) is available on the machine running the toolchain.
Instead of the self extracting shell script save the config as a regular compressed file with an obvious file extension.
=> scripts: Save toolchain config as regular file

packages/gcc/14.2.0/0011-aarch64-Fix-invalid-nested-subregs-PR115464.patch, packages/gcc/14.2.0/0012-aarch64-Use-force_subreg-in-more-places.patch, packages/gcc/14.2.0/0013-aarch64-Add-some-uses-of-force_lowpart_subreg.patch, packages/gcc/14.2.0/0014-Add-force_lowpart_subreg.patch, packages/gcc/14.2.0/0015-Make-more-use-of-force_subreg.patch, packages/gcc/14.2.0/0016-Revert-one-of-the-force_subreg-changes.patch
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=115464 for issue description and list of patches to backport.
=> gcc-14.2: Fix ICE on aarch64

scripts/build/companion_libs/070-zstd.sh
We have been building the multi threaded zstd target. This requires that anything that links with lzstd also links with lpthread. On more recent systems this is fine because lpthread is part of GNU libc so the -pthread option is a no-op but on other systems this will cause GCC to either fail to build or to silently disable zstd compression. By building the libzstd.a-nomt-release we can be compatible with older GCC versions and ensure that support for zstd is not silently dropped.
Fixes: #2198
=> companion_libs: zstd: Build nomt configuration

config/libc/glibc.in
Versions of GNU make newer than 4.4 trigger a hang in versions of glibc older than 2.31. In e63c40854c977f488bee159a8f8ebf5fc06c8666, this was fixed when the host platform provided make >= 4.4. However, if the host distro provides only an ancient version of make, crosstool-ng would still build make 4.4 as a comp tool, which would fail to build glibc.
Extend the previous workaround to build make 4.3 when building old glibc versions which require it.
See also #1946
=> improve a workaround for a glibc and GNU make incompatibility

.github/workflows/continuous-integration-workflow.yml
Meson and Ninja are used by picolibc. Explicitly install these tools which we appear to have been getting by some transitive dependency up to now.
=> CI: Install meson and ninja for macOS

scripts/build/cc/gcc.sh, scripts/crosstool-NG.sh
When building a non-sysrooted toolchain, `--with-headers` argument is specified in `CT_CC_SYSROOT_ARG` as a hack, supposedly because "final gcc will define disable_glibc while building libgcc, and you'll have no profiling."
This, however, leads to `--with-headers` being specified multiple times when building libstdc++ for additional libc variants (e.g. newlib-nano and picolibc) and results in wrong libc headers being used by the libstdc++ build under certain circumstances -- GCC does not use the last specified `--with-headers` when building for macOS and Windows hosts.
Since the above hack is intended for glibc only, this commit adds a check to ensure that `--with-headers` is added to `CT_CC_SYSROOT_ARG` only when building glibc.
In addition, the final gcc build process was relying on …
=> Specify header path in CT_CC_SYSROOT_ARG only for glibc

config/libc/glibc.in
As of GCC14 implicit-int has been upgraded to an error. While this is generally a good idea it trips up some older code (particularly in autoconf generated configure scripts). Add -Wno-implicit-int to CFLAGS for glibc when using an old GLIBC with a new GCC.
Fixes #2208
=> glibc: Turn implicit-int back into warning

scripts/build/debug/300-gdb.sh
GDB_CC_LD_LIBTOOL don't exist and so always use else branch. We should use CT_GDB_CC_LD_LIBTOOL.
=> gdb: fix GDB_CC_LD_LIBTOOL reference

config/global/download.in
In some distributions (as Fedora), wget2 is used instead of wget. wget2 doesn't support the --passive-ftp option causing every download to fail. Also, according to wget's NEWS file [0], --passive-ftp is already the default in wget since 1.10.
Remove the --passive-ftp from wget's default options.
[0] https://gitlab.com/gnuwget/wget/-/blob/master/NEWS#L733
=> Drop --passive-ftp from wget's default options

scripts/build/linker/100-mold.sh
The mold build was using gcc in the PATH, instead of the shiny gcc we just built (the way the other companion libs/tools do)
=> mold: tell cmake which compilers to use

.github/workflows/build-toolchains.yml, .github/workflows/continuous-integration-workflow.yml
GitHub has dropped support for macos-12.
https://github.com/actions/runner-images/issues/10721
We had problems with macos-14 when it was first rolled out. Lets give macos-13 a try. We'll probably have to migrate to macos-14 or macos-15 eventually but hopefully we can leave that until after the ct-ng 1.27.0 release.
=> CI: switch to macos-13 runners

scripts/build/debug/300-gdb.sh
* pass libexpat configuration for static building of native gdb
* change flags for static build to generate static binaries with different linkers of gdb and gdbserver
=> Configuration for building static native gdb packages.

config/cc/gcc.in, scripts/build/cc/gcc.sh, scripts/build/libc/avr-libc.sh
Should not cause major unwanted behavior changes
- C++ is now selected by default in many configs.
I think many people would select C++ either way, and you can still disable it
=> Cleanup old avr-libstdcxx code and make it usable on other targets

scripts/build/companion_libs/340-picolibc.sh
When building picolibc as a companion library the configure step can end up picking up certain headers from the build system which causes build failures. Pass an appropriate --with-headers= to the GCC back end when building picolibc as a companion library so that the correct headers are detected by ./configure.
=> picolibc: Avoid build system headers

samples/tic6x-uclinux/crosstool.config
The custom uclibc has compile errors with GCC 14. Ignoring that even a bare metal config fails to build (assembler errors in libgcc) with GCC
14. For now pin the sample config to GCC 13 since that seems to work.
=> c6x: pin to GCC 13

config/arch/nios2.in
Previous commits added selects so that the nios2 architecture only used GDB/GLIBC versions that still support it however these weren't qualified leading to kconfig complaints such as
WARNING: unmet direct dependencies detected for GLIBC_REQUIRE_older_than_2_41
Depends on [n]: LIBC_GLIBC_SHOW [=n]
Selected by [y]:
- ARCH_NIOS2 [=y] && GEN_CHOICE_ARCH [=y]
Qualify these selects with if DEBUG_GDB and if LIBC_GLIBC to stop the complaints.
Fixes: 9d91cebe ("gdb: Add 16.1")
Fixes: 87605d65 ("glibc: Add 2.41")
=> arch: nios2: Qualify selects

packages/gmp/6.3.0/0000-Complete-function-prototype-in-acinclude.patch
Add a patch from upstream GMP that updates some custom configure checks for C23 compatibility (gnu32 will be the default for GCC 15).
Reported-by: Marc Poulhiès <dkm@kataplop.net>
=> gmp: Add upstream patch for C23 compatibility

Makefile.am
Currently this package is not fully reproducible on arch linux. See the [diffoscope](https://reproducible.archlinux.org/api/v0/builds/594872/diffoscope).
The issue is the recorded timestamp in the gzip header which can easily be ignored with the [no-name](https://wiki.debian.org/ReproducibleBuilds/TimestampsInGzipHeaders) flag for gzip.
=> Make package reproducible on arch linux

config/binutils/binutils.in
A static toolchain by definition can't load plugins and GCC will reject the --enable-plugin configure option if we're trying to build a static toolchain.
Fixes #2288
=> binutils: Don't enable plugins with static toolchain

packages/gcc/12.4.0/0011-always-define-win32-lean-and-mean-before-windows-h.patch
This patch defines `WIN32_LEAN_AND_MEAN` before the `windows.h` include statements to avoid name clashes with the `abort()` member function in `IXMLDOMDocument`, which would now be pulled in via `msxml.h` without the `WIN32_LEAN_AND_MEAN` definition.
=> Add patch for GCC 12.4.0 to make it compatible with MinGW >=11

scripts/build/companion_libs/220-ncurses.sh
The default for wide char support has changed in ncurses-6.5. This causes build failures for gdb. Pass --disable-widec to prevent the build errors.
Fixes #2292, #2294
=> ncurses: Pass --disable-widec to configure

config/contrib/gcc-test-suite.in, config/test_suite.in, contrib/gcc-test-suite/Makefile, contrib/gcc-test-suite/default.cfg, scripts/build/test_suite/gcc.sh
This makes the options necessary to run the gcc test suite configurable in the crosstool-ng config file.
That includes the ability to run the test suite using qemu instead of on a remote host.
=> contrib/gcc-test-suite: Add configuration options including qemu setup

scripts/build/cc/gcc.sh
I made a wrong assumption about Kconfig in #2237, this fixes that.
The config var is unset and not just `n`.
=> Fix disabled libstdc++-v3

packages/glibc/2.29/0005-riscv-Fix-incorrect-jal-with-HIDDEN_JUMPTARGET.patch, packages/glibc/2.30/0005-riscv-Fix-incorrect-jal-with-HIDDEN_JUMPTARGET.patch, packages/glibc/2.31/0004-riscv-Fix-incorrect-jal-with-HIDDEN_JUMPTARGET.patch, packages/glibc/2.32/0004-riscv-Fix-incorrect-jal-with-HIDDEN_JUMPTARGET.patch, packages/glibc/2.33/0004-riscv-Fix-incorrect-jal-with-HIDDEN_JUMPTARGET.patch, packages/glibc/2.34/0003-riscv-Fix-incorrect-jal-with-HIDDEN_JUMPTARGET.patch
This fixes BFD assertion fail in elfnn-riscv.c when building glibc 2.29~2.34 with binutils(e.g. version 2.40 used in #2270).
Versions older than 2.29 have merge conflicts with this patch so they are not taken care of. (And I don't think anyone will be interested in them as riscv64 support is introduced in 2.27)
Close #2270
=> glibc/riscv: Fix incorrect jal with HIDDEN_JUMPTARGET

packages/gcc/7.5.0/0031-riscv-Add-.type-and-.size-directives-to-riscv-libgcc-funct.patch, packages/gcc/7.5.0/0032-riscv-Make-__divdi3-handle-div-by-zero-same-as-hard.patch, packages/gcc/7.5.0/0033-riscv-jal-cannot-refer-to-a-default-visibility-symb.patch, packages/gcc/8.5.0/0033-riscv-Make-__divdi3-handle-div-by-zero-same-as-hard.patch, packages/gcc/8.5.0/0034-riscv-jal-cannot-refer-to-a-default-visibility-symb.patch, packages/gcc/9.5.0/0031-riscv-Make-__divdi3-handle-div-by-zero-same-as-hard.patch, packages/gcc/9.5.0/0032-riscv-jal-cannot-refer-to-a-default-visibility-symb.patch
Similar to #2315, backport commit [45116f3](https://github.com/gcc-mirror/gcc/commit/45116f342057b7facecd3d05c2091ce3a77eda59) and dependent patches for gcc 7,8,9.
Fixes:
```text
[ALL  ]    /usr/riscv64-unknown-linux-gnu/riscv64-unknown-linux-gnu/bin/ld: relocation R_RISCV_JAL against `__udivdi3' which may bind externally can not be used when making a shared object; recompile with -fPIC
[ERROR]    collect2: error: ld returned 1 exit status
[ERROR]    make[4]: *** [Makefile:982: libgcc_s.so] Error 1
```
GCC 7 is the first version to support RISC-V.
=> gcc/riscv: Fix incorrect jal with HIDDEN_JUMPTARGET

samples/mips64-ol9u5-linux-gnu/crosstool.config
Hello, the previous version of this sample would build successfully for ol9 (and Ubuntu LTS), but not ol8. This allows for building on ol8, as well as the other platforms.
=> Pie fix ol8

.github/workflows/continuous-integration-workflow.yml
Use arm-none-eabi instead of arm-picolibc-eabi. The none-eabi configuration includes picolibc and newlib so it will ensure both are downloaded.
=> CI: Use arm-none-eabi to get newlib tarball

config/cc/gcc.in, config/comp_libs/picolibc.in, scripts/build/cc/gcc.sh, scripts/build/companion_libs/340-picolibc.sh
Newlib-nano has a configuration variable which controls additional flags used when building libstdc++, such as `-fno-exceptions`.  Add two new variables to allow this to be added to any libstdc++ build as well as to the picolibc-specific build when picolibc is added as a companion library: `CC_GCC_LIBSTDCXX_TARGET_CXXFLAGS` and `LIBC_PICOLIBC_GCC_LIBSTDCXX_TARGET_CXXFLAGS`
=> gcc: Allow addition of -fno-exceptions when building libstdc++

packages/ncurses/6.2/0001-MKlib_gen-Handle-gcc-version-containing-too.patch
As the patch itself says, debian's mingw32 toolchains set the gcc version number to <version>-win32 or <version>-posix. That messes up ncurses version detection which only looks for a `.`. With this patch, I was able to build a canadian cross compiler on Linux that runs on windows and builds arm binaries.
=> Add ncurses patch to handle debian mingw32 toolchain

packages/newlib/4.5.0.20241231/0000-libgloss-rs6000-Add-missing-function-prototypes.patch
Add a patch to resolve some errors for powerpc-unknown-elf configurations.
Submitted upstream as https://sourceware.org/pipermail/newlib/2025/021708.html
=> newlib: Add patch for powerpc errors

config/libc/glibc.in
As of glibc-2.39, the HAS_OBSOLETE_LIBCRYPT option has been removed.
This patch updates menuconfig to reflect this.
See more in glibc's release notes at https://lists.gnu.org/archive/html/info-gnu/2024-01/msg00017.html
=> Fixes false indication of glibc's option HAS_OBSOLETE_LIBCRYPT

packages/gmp/6.3.0/0000-Complete-function-prototype-in-acinclude.patch
The patch added in 1e9bf8151513b054f60f34bc89507c31dc242cf0 changes the definition of the function `g` used in `configure` tests from `void g(){}` to `void g(int,t1 const*,t1,t2,t1 const*,int){}`.
However, omitting parameter names in function definitions is a C23 feature. This thus causes configuration to fail with a GCC 9 host compiler:
```c
conftest.c: In function 'g':
conftest.c:7:8: error: parameter name omitted
7 | void g(int,t1 const*,t1,t2,t1 const*,int){}
|        ^~~
conftest.c:7:12: error: parameter name omitted
7 | void g(int,t1 const*,t1,t2,t1 const*,int){}
|            ^~~~~~~~~
conftest.c:7:22: error: parameter name omitted
7 | void g(int,t1 const*,t1,t2,t1 const*,int){}
|                      ^~
conftest.c:7:25: error: parameter name omitted
7 | void g(int,t1 …
```
=> gmp: Fix C23 compatibility patch to work with older host compilers

scripts/build/cc/gcc.sh
This was added to do_gcc_core_backend but not do_gcc_backend so the final compiler didn't have the configuration. Fix this so that the setting affects bot the core and final compilers.
Fixes #2632
=> gcc: Add default pie support to do_gcc_backend

packages/expat/package.desc
The bootstrap command generates the configure script, which is then used as part of the standard build process. It's not possible to run make because configure hasn't been run to generate the required makefiles. Remove the `make` command from the expat bootstrap.
Fixes #2379
=> expat: Use correct bootstrap command

config/libc/glibc.in, scripts/build/libc/glibc.sh
Newer versions of makeinfo fail to build the older versions of the glibc manual triggering build failures. Add a workaround for this my disabling makeinfo for the glibc build where needed.
Fixes #2358
=> libc/glibc: Add workaround for makeinfo build issue

config/comp_libs/gmp.in, config/comp_libs/ncurses.in, scripts/build/companion_libs/100-gmp.sh, scripts/build/companion_libs/220-ncurses.sh
Use -std=c17 for companion libs, which won't build with C23 standard, default for gcc15
=> Build companions on gcc15

packages/mingw-w64/v11.0.1/0001-crt-ssp-fix-stack-smashing-protection-bootstrapping.patch, packages/mingw-w64/v12.0.0/0001-crt-ssp-fix-stack-smashing-protection-bootstrapping.patch
Cherry-picked a fix for mingw-w64 lib, particularly the init function for the stack smashing protection feature.
The issue occurs when mingw lib is compiled using gcc's flag: -fstack-protector-strong
Upstream mail list thread with accepted patch:
https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/20250703120657.1092-1-work.kerogi%40gmail.com/
=> mingw-w64/crt: bring patch with the fix of the stack smashing protection

packages/gdb/15.2/0000-readline-bring-in-signal.c-from-gdb-16-branch.patch, packages/gdb/15.2/0001-readline-tcap.h-Update-definitions-for-C23.patch
Remove a nonexistent function call and keep janitorial changes only. Add missing patch for tcap.h
=> gdb: fix readline for gdb 15.2

scripts/build/arch/sh.sh
- it had an extra `-` at the end when there is no fpu/mmu suffix
- a second underscore like in `_single_only` would not get converted
Fixes #2415
=> Fix CT_ARCH_ARCH_CFLAG for SuperH in some cases

README.md
Remove a note about uClibc and crosstool-ng-1.21.0.
=> README.md: Remove old note
